# **Exploração da API do The Cancer Genome Atlas (TCGA)**
Desenvolvida pela Genomic Data Commons (GDC)

# Importação de Bibliotecas

In [1]:
import json
import pandas as pd
import requests

# Constantes

In [2]:
# URL HTML base da API TCGA / GDC
TCGA_API_ENDPOINT = 'https://api.gdc.cancer.gov'

# "Search annotations added to data after curation"
ANNOTATIONS_ENDPOINT = f'{TCGA_API_ENDPOINT}/annotations'

# "Find all files related to a specific case, or sample donor"
CASES_ENDPOINT = f'{TCGA_API_ENDPOINT}/cases'

# "Used to download GDC data"
DATA_ENDPOINT = f'{TCGA_API_ENDPOINT}/data'

# "Find all files with specific characteristics such as file_name, md5sum, data_format and others"
FILES_ENDPOINT = f'{TCGA_API_ENDPOINT}/files'

# "Generates manifests for use with GDC Data Transfer Tool"
MANIFEST_ENDPOINT = f'{TCGA_API_ENDPOINT}/manifest'

# "Search all data generated by a project"
PROJECTS_ENDPOINT = f'{TCGA_API_ENDPOINT}/projects'

# "Allows remote slicing of BAM format objects"
SLICING_ENDPOINT = f'{TCGA_API_ENDPOINT}/slicing'

# "Get the API status and version information"
STATUS_ENDPOINT = f'{TCGA_API_ENDPOINT}/status'

# "Returns the available resources at the top level above programs i.e., registered programs"
SUBMISSION_ENDPOINT = f'{TCGA_API_ENDPOINT}/submission'

# Exploração Inicial dos Endpoints

## `status`

In [3]:
# Verifica o status e a versão da API
response = requests.get(STATUS_ENDPOINT)

# Printa o conteúdo da resposta
print(response.content.decode('utf-8'))

{"commit":"3ed4235efe2f2d9c9969e1ce790e6b34a5c60c9d","data_release":"Data Release 40.0 - March 29, 2024","status":"OK","tag":"7.4.0","version":1}

In [4]:
# Campos disponíveis no endpoint
fields = [
    'annotation_autocomplete',
    'annotation_id',
    'case_id',
    'case_submitter_id',
    'category',
    'classification',
    'created_datetime',
    'entity_id',
    'entity_submitter_id',
    'entity_type',
    'legacy_created_datetime',
    'legacy_updated_datetime',
    'notes',
    'project.code',
    'project.dbgap_accession_number',
    'project.disease_type',
    'project.intended_release_date',
    'project.name',
    'project.primary_site',
    'project.program.dbgap_accession_number',
    'project.program.name',
    'project.program.program_id',
    'project.project_id',
    'project.releasable',
    'project.released',
    'project.state',
    'state',
    'status',
    'submitter_id',
    'updated_datetime'
]
fields = ','.join(fields)

# Busca por todos os projetos da API
response = requests.post(
    url=ANNOTATIONS_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Printa um dos objetos do conteúdo da resposta
json_response_str = json.dumps(json_response[1], indent=2)
print(json_response_str)

{
  "id": "8c55e871-68a3-47dd-a51b-b1205ec01d5d",
  "entity_submitter_id": "169aa9ac-64e7-4e82-a4ac-82fa430b7f64",
  "notes": "Real somatic mutations were mistakenly labeled as LOH (Loss of Heterozygosity) in certain SomaticSniper VCF files.",
  "project": {
    "primary_site": [
      "Connective, subcutaneous and other soft tissues",
      "Other and unspecified parts of tongue",
      "Other and unspecified parts of biliary tract",
      "Other and unspecified parts of mouth",
      "Rectum",
      "Uterus, NOS",
      "Pancreas",
      "Corpus uteri",
      "Other and ill-defined sites",
      "Gallbladder",
      "Breast",
      "Kidney",
      "Nasal cavity and middle ear",
      "Liver and intrahepatic bile ducts",
      "Rectosigmoid junction",
      "Stomach",
      "Bronchus and lung",
      "Colon",
      "Ovary",
      "Bones, joints and articular cartilage of other and unspecified sites",
      "Skin",
      "Small intestine",
      "Esophagus",
      "Brain"
    ],
    "dbgap_accession_number": null,
    "project_id": "HCMI-CMDC",
    "disease_type": [
      "Complex Mixed and Stromal Neoplasms",
      "Acinar Cell Neoplasms",
      "Adenomas and Adenocarcinomas",
      "Squamous Cell Neoplasms",
      "Gliomas",
      "Fibromatous Neoplasms",
      "Soft Tissue Tumors and Sarcomas, NOS",
      "Myomatous Neoplasms",
      "Blood Vessel Tumors",
      "Osseous and Chondromatous Neoplasms",
      "Ductal and Lobular Neoplasms",
      "Cystic, Mucinous and Serous Neoplasms",
      "Miscellaneous Bone Tumors",
      "Nevi and Melanomas",
      "Complex Epithelial Neoplasms",
      "Epithelial Neoplasms, NOS"
    ],
    "name": "NCI Cancer Model Development for the Human Cancer Model Initiative",
    "releasable": true,
    "state": "open",
    "program": {
      "dbgap_accession_number": "phs001486",
      "program_id": "a5448c11-d46a-56aa-a5e1-5c1aa06404df",
      "name": "HCMI"
    },
    "released": true
  },
  "classification": "Notification",
  "entity_id": "9e20ce90-0be0-4964-b4c7-94d73daceeef",
  "created_datetime": "2022-02-27T21:15:39.773153-06:00",
  "annotation_id": "8c55e871-68a3-47dd-a51b-b1205ec01d5d",
  "entity_type": "simple_somatic_mutation",
  "updated_datetime": "2023-02-22T07:39:25.979291-06:00",
  "case_id": "0e9a9e97-f0bf-4f4a-84cc-73eccfc627b1",
  "state": "released",
  "category": "General",
  "status": "Approved",
  "case_submitter_id": "HCM-CSHL-0376-D37"
}

## `projects`

In [5]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{PROJECTS_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON e a printa
json_response = json.loads(response.content.decode('utf-8'))
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

{
  "_mapping": {
    "projects.dbgap_accession_number": {
      "description": "",
      "doc_type": "projects",
      "field": "dbgap_accession_number",
      "full": "projects.dbgap_accession_number",
      "type": "keyword"
    },
    "projects.disease_type": {
      "description": "",
      "doc_type": "projects",
      "field": "disease_type",
      "full": "projects.disease_type",
      "type": "keyword"
    },
    "projects.intended_release_date": {
      "description": "",
      "doc_type": "projects",
      "field": "intended_release_date",
      "full": "projects.intended_release_date",
      "type": "keyword"
    },
    "projects.name": {
      "description": "",
      "doc_type": "projects",
      "field": "name",
      "full": "projects.name",
      "type": "keyword"
    },
    "projects.primary_site": {
      "description": "",
      "doc_type": "projects",
      "field": "primary_site",
      "full": "projects.primary_site",
      "type": "keyword"
    },
    "projects.program.dbgap_accession_number": {
      "description": "The dbgap accession number provided for the program.",
      "doc_type": "projects",
      "field": "program.dbgap_accession_number",
      "full": "projects.program.dbgap_accession_number",
      "type": "keyword"
    },
    "projects.program.name": {
      "description": "Full name/title of the program.",
      "doc_type": "projects",
      "field": "program.name",
      "full": "projects.program.name",
      "type": "keyword"
    },
    "projects.program.program_id": {
      "description": "",
      "doc_type": "projects",
      "field": "program.program_id",
      "full": "projects.program.program_id",
      "type": "keyword"
    },
    "projects.project_autocomplete": {
      "description": "",
      "doc_type": "projects",
      "field": "project_autocomplete",
      "full": "projects.project_autocomplete",
      "type": "id"
    },
    "projects.project_id": {
      "description": "",
      "doc_type": "projects",
      "field": "project_id",
      "full": "projects.project_id",
      "type": "keyword"
    },
    "projects.releasable": {
      "description": "",
      "doc_type": "projects",
      "field": "releasable",
      "full": "projects.releasable",
      "type": "keyword"
    },
    "projects.released": {
      "description": "",
      "doc_type": "projects",
      "field": "released",
      "full": "projects.released",
      "type": "keyword"
    },
    "projects.state": {
      "description": "",
      "doc_type": "projects",
      "field": "state",
      "full": "projects.state",
      "type": "keyword"
    },
    "projects.summary.case_count": {
      "description": "",
      "doc_type": "projects",
      "field": "summary.case_count",
      "full": "projects.summary.case_count",
      "type": "long"
    },
    "projects.summary.data_categories.case_count": {
      "description": "",
      "doc_type": "projects",
      "field": "summary.data_categories.case_count",
      "full": "projects.summary.data_categories.case_count",
      "type": "long"
    },
    "projects.summary.data_categories.data_category": {
      "description": "",
      "doc_type": "projects",
      "field": "summary.data_categories.data_category",
      "full": "projects.summary.data_categories.data_category",
      "type": "keyword"
    },
    "projects.summary.data_categories.file_count": {
      "description": "",
      "doc_type": "projects",
      "field": "summary.data_categories.file_count",
      "full": "projects.summary.data_categories.file_count",
      "type": "long"
    },
    "projects.summary.experimental_strategies.case_count": {
      "description": "",
      "doc_type": "projects",
      "field": "summary.experimental_strategies.case_count",
      "full": "projects.summary.experimental_strategies.case_count",
      "type": "long"
    },
    "projects.summary.experimental_strategies.experimental_strategy": {
      "description": "",
      "doc_type": "projects",
      "field": "summary.experimental_strategies.experimental_strategy",
      "full": "projects.summary.experimental_strategies.experimental_strategy",
      "type": "keyword"
    },
    "projects.summary.experimental_strategies.file_count": {
      "description": "",
      "doc_type": "projects",
      "field": "summary.experimental_strategies.file_count",
      "full": "projects.summary.experimental_strategies.file_count",
      "type": "long"
    },
    "projects.summary.file_count": {
      "description": "",
      "doc_type": "projects",
      "field": "summary.file_count",
      "full": "projects.summary.file_count",
      "type": "long"
    },
    "projects.summary.file_size": {
      "description": "",
      "doc_type": "projects",
      "field": "summary.file_size",
      "full": "projects.summary.file_size",
      "type": "long"
    }
  },
  "defaults": [
    "dbgap_accession_number",
    "disease_type",
    "intended_release_date",
    "name",
    "primary_site",
    "project_autocomplete",
    "project_id",
    "releasable",
    "released",
    "state"
  ],
  "expand": [
    "program",
    "summary",
    "summary.data_categories",
    "summary.experimental_strategies"
  ],
  "fields": [
    "dbgap_accession_number",
    "disease_type",
    "intended_release_date",
    "name",
    "primary_site",
    "program.dbgap_accession_number",
    "program.name",
    "program.program_id",
    "project_autocomplete",
    "project_id",
    "releasable",
    "released",
    "state",
    "summary.case_count",
    "summary.data_categories.case_count",
    "summary.data_categories.data_category",
    "summary.data_categories.file_count",
    "summary.experimental_strategies.case_count",
    "summary.experimental_strategies.experimental_strategy",
    "summary.experimental_strategies.file_count",
    "summary.file_count",
    "summary.file_size"
  ],
  "multi": [],
  "nested": [
    "summary.data_categories",
    "summary.experimental_strategies"
  ]
}

In [6]:
# Campos disponíveis no endpoint
fields = [
    'dbgap_accession_number',
    'disease_type',
    'intended_release_date',
    'name',
    'primary_site',
    'program.dbgap_accession_number',
    'program.name',
    'program.program_id',
    'project_autocomplete',
    'project_id',
    'releasable',
    'released',
    'state',
    'summary.case_count',
    'summary.data_categories.case_count',
    'summary.data_categories.data_category',
    'summary.data_categories.file_count',
    'summary.experimental_strategies.case_count',
    'summary.experimental_strategies.experimental_strategy',
    'summary.experimental_strategies.file_count',
    'summary.file_count',
    'summary.file_size'
]
fields = ','.join(fields)

# Busca por todos os projetos da API
response = requests.post(
    url=PROJECTS_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Printa um dos objetos do conteúdo da resposta
json_response_str = json.dumps(json_response[1], indent=2)
print(json_response_str)

{
  "id": "TCGA-BRCA",
  "summary": {
    "file_count": 61173,
    "data_categories": [
      {
        "file_count": 17337,
        "case_count": 1098,
        "data_category": "Simple Nucleotide Variation"
      },
      {
        "file_count": 9281,
        "case_count": 1098,
        "data_category": "Sequencing Reads"
      },
      {
        "file_count": 5316,
        "case_count": 1098,
        "data_category": "Biospecimen"
      },
      {
        "file_count": 2288,
        "case_count": 1098,
        "data_category": "Clinical"
      },
      {
        "file_count": 12292,
        "case_count": 1098,
        "data_category": "Copy Number Variation"
      },
      {
        "file_count": 4876,
        "case_count": 1097,
        "data_category": "Transcriptome Profiling"
      },
      {
        "file_count": 3714,
        "case_count": 1097,
        "data_category": "DNA Methylation"
      },
      {
        "file_count": 919,
        "case_count": 881,
        "data_category": "Proteome Profiling"
      },
      {
        "file_count": 226,
        "case_count": 101,
        "data_category": "Somatic Structural Variation"
      },
      {
        "file_count": 4924,
        "case_count": 1095,
        "data_category": "Structural Variation"
      }
    ],
    "experimental_strategies": [
      {
        "file_count": 11079,
        "case_count": 1095,
        "experimental_strategy": "RNA-Seq"
      },
      {
        "file_count": 17049,
        "case_count": 1072,
        "experimental_strategy": "WXS"
      },
      {
        "file_count": 3621,
        "case_count": 1079,
        "experimental_strategy": "miRNA-Seq"
      },
      {
        "file_count": 2783,
        "case_count": 952,
        "experimental_strategy": "WGS"
      },
      {
        "file_count": 75,
        "case_count": 74,
        "experimental_strategy": "ATAC-Seq"
      },
      {
        "file_count": 14329,
        "case_count": 1098,
        "experimental_strategy": "Genotyping Array"
      },
      {
        "file_count": 3714,
        "case_count": 1097,
        "experimental_strategy": "Methylation Array"
      },
      {
        "file_count": 919,
        "case_count": 881,
        "experimental_strategy": "Reverse Phase Protein Array"
      },
      {
        "file_count": 1133,
        "case_count": 1062,
        "experimental_strategy": "Diagnostic Slide"
      },
      {
        "file_count": 1978,
        "case_count": 1093,
        "experimental_strategy": "Tissue Slide"
      }
    ],
    "case_count": 1098,
    "file_size": 624536203965423
  },
  "primary_site": [
    "Breast"
  ],
  "dbgap_accession_number": null,
  "project_id": "TCGA-BRCA",
  "disease_type": [
    "Cystic, Mucinous and Serous Neoplasms",
    "Complex Epithelial Neoplasms",
    "Ductal and Lobular Neoplasms",
    "Squamous Cell Neoplasms",
    "Adenomas and Adenocarcinomas",
    "Basal Cell Neoplasms",
    "Epithelial Neoplasms, NOS",
    "Adnexal and Skin Appendage Neoplasms",
    "Fibroepithelial Neoplasms"
  ],
  "name": "Breast Invasive Carcinoma",
  "releasable": true,
  "state": "open",
  "program": {
    "dbgap_accession_number": "phs000178",
    "program_id": "b80aa962-9650-5110-b3eb-bd087da808db",
    "name": "TCGA"
  },
  "released": true
}

## `cases`

In [7]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{CASES_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON e a printa
json_response = json.loads(response.content.decode('utf-8'))
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

{
  "_mapping": {
    "cases.aliquot_ids": {
      "description": "",
      "doc_type": "cases",
      "field": "aliquot_ids",
      "full": "cases.aliquot_ids",
      "type": "keyword"
    },
    "cases.analyte_ids": {
      "description": "",
      "doc_type": "cases",
      "field": "analyte_ids",
      "full": "cases.analyte_ids",
      "type": "keyword"
    },
    "cases.annotations.annotation_id": {
      "description": "",
      "doc_type": "cases",
      "field": "annotations.annotation_id",
      "full": "cases.annotations.annotation_id",
      "type": "keyword"
    },
    "cases.annotations.case_id": {
      "description": "",
      "doc_type": "cases",
      "field": "annotations.case_id",
      "full": "cases.annotations.case_id",
      "type": "keyword"
    },
    "cases.annotations.case_submitter_id": {
      "description": "",
      "doc_type": "cases",
      "field": "annotations.case_submitter_id",
      "full": "cases.annotations.case_submitter_id",
      "type": "keyword"
    },
    "cases.annotations.category": {
      "description": "Top level characterization of the annotation.",
      "doc_type": "cases",
      "field": "annotations.category",
      "full": "cases.annotations.category",
      "type": "keyword"
    },
    "cases.annotations.classification": {
      "description": "Top level classification of the annotation.",
      "doc_type": "cases",
      "field": "annotations.classification",
      "full": "cases.annotations.classification",
      "type": "keyword"
    },
    "cases.annotations.created_datetime": {
      "description": "A combination of date and time of day in the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]",
      "doc_type": "cases",
      "field": "annotations.created_datetime",
      "full": "cases.annotations.created_datetime",
      "type": "keyword"
    },
    "cases.annotations.creator": {
      "description": "Name of the person or entity responsible for the creation of the annotation.",
      "doc_type": "cases",
      "field": "annotations.creator",
      "full": "cases.annotations.creator",
      "type": "keyword"
    },
    "cases.annotations.entity_id": {
      "description": "",
      "doc_type": "cases",
      "field": "annotations.entity_id",
      "full": "cases.annotations.entity_id",
      "type": "keyword"
    },
    "cases.annotations.entity_submitter_id": {
      "description": "",
      "doc_type": "cases",
      "field": "annotations.entity_submitter_id",
      "full": "cases.annotations.entity_submitter_id",
      "type": "keyword"
    },
    "cases.annotations.entity_type": {
      "description": "",
      "doc_type": "cases",
      "field": "annotations.entity_type",
      "full": "cases.annotations.entity_type",
      "type": "keyword"
    },
    "cases.annotations.legacy_created_datetime": {
      "description": "A combination of date and time of day in the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]",
      "doc_type": "cases",
      "field": "annotations.legacy_created_datetime",
      "full": "cases.annotations.legacy_created_datetime",
      "type": "keyword"
    },
    "cases.annotations.legacy_updated_datetime": {
      "description": "A combination of date and time of day in the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]",
      "doc_type": "cases",
      "field": "annotations.legacy_updated_datetime",
      "full": "cases.annotations.legacy_updated_datetime",
      "type": "keyword"
    },
    "cases.annotations.notes": {
      "description": "Open entry for any further description or characterization of the data.",
      "doc_type": "cases",
      "field": "annotations.notes",
      "full": "cases.annotations.notes",
      "type": "keyword"
    },
    "cases.annotations.state": {
      "description": "The current state of the object.",
      "doc_type": "cases",
      "field": "annotations.state",
      "full": "cases.annotations.state",
      "type": "keyword"
    },
    "cases.annotations.status": {
      "description": "Status of the annotation.",
      "doc_type": "cases",
      "field": "annotations.status",
      "full": "cases.annotations.status",
      "type": "keyword"
    },
    "cases.annotations.submitter_id": {
      "description": "A project-specific identifier for a node. This property is the calling card/nickname/alias for a unit of submission. It can be used in place of the uuid for identifying or recalling a node.",
      "doc_type": "cases",
      "field": "annotations.submitter_id",
      "full": "cases.annotations.submitter_id",
      "type": "keyword"
    },
    "cases.annotations.updated_datetime": {
      "description": "A combination of date and time of day in the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]",
      "doc_type": "cases",
      "field": "annotations.updated_datetime",
      "full": "cases.annotations.updated_datetime",
      "type": "keyword"
    },
    "cases.case_autocomplete": {
      "description": "",
      "doc_type": "cases",
      "field": "case_autocomplete",
      "full": "cases.case_autocomplete",
      "type": "id"
    },
    "cases.case_id": {
      "description": "",
      "doc_type": "cases",
      "field": "case_id",
      "full": "cases.case_id",
      "type": "keyword"
    },
    "cases.consent_type": {
      "description": "",
      "doc_type": "cases",
      "field": "consent_type",
      "full": "cases.consent_type",
      "type": "keyword"
    },
    "cases.created_datetime": {
      "description": "",
      "doc_type": "cases",
      "field": "created_datetime",
      "full": "cases.created_datetime",
      "type": "keyword"
    },
    "cases.days_to_consent": {
      "description": "",
      "doc_type": "cases",
      "field": "days_to_consent",
      "full": "cases.days_to_consent",
      "type": "long"
    },
    "cases.days_to_lost_to_followup": {
      "description": "",
      "doc_type": "cases",
      "field": "days_to_lost_to_followup",
      "full": "cases.days_to_lost_to_followup",
      "type": "long"
    },
    "cases.demographic.age_at_index": {
      "description": "The patient's age (in years) on the reference or anchor date used during date obfuscation.",
      "doc_type": "cases",
      "field": "demographic.age_at_index",
      "full": "cases.demographic.age_at_index",
      "type": "long"
    },
    "cases.demographic.age_is_obfuscated": {
      "description": "The age or other properties related to the patient's age have been modified for compliance reasons. The actual age may differ from what was reported in order to comply with the Health Insurance Portability and Accountability Act (HIPAA).",
      "doc_type": "cases",
      "field": "demographic.age_is_obfuscated",
      "full": "cases.demographic.age_is_obfuscated",
      "type": "keyword"
    },
    "cases.demographic.cause_of_death": {
      "description": "Text term to identify the cause of death for a patient.",
      "doc_type": "cases",
      "field": "demographic.cause_of_death",
      "full": "cases.demographic.cause_of_death",
      "type": "keyword"
    },
    "cases.demographic.cause_of_death_source": {
      "description": "The text term used to describe the source used to determine the patient's cause of death.",
      "doc_type": "cases",
      "field": "demographic.cause_of_death_source",
      "full": "cases.demographic.cause_of_death_source",
      "type": "keyword"
    },
    "cases.demographic.country_of_birth": {
      "description": "The name of the country in which the patient is born.",
      "doc_type": "cases",
      "field": "demographic.country_of_birth",
      "full": "cases.demographic.country_of_birth",
      "type": "keyword"
    },
    "cases.demographic.country_of_residence_at_enrollment": {
      "description": "The text term used to describe the patient's country of residence at the time they were enrolled in the study.",
      "doc_type": "cases",
      "field": "demographic.country_of_residence_at_enrollment",
      "full": "cases.demographic.country_of_residence_at_enrollment",
      "type": "keyword"
    },
    "cases.demographic.created_datetime": {
      "description": "A combination of date and time of day in the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]",
      "doc_type": "cases",
      "field": "demographic.created_datetime",
      "full": "cases.demographic.created_datetime",
      "type": "keyword"
    },
    "cases.demographic.days_to_birth": {
      "description": "Number of days between the date used for index and the date from a person's date of birth represented as a calculated negative number of days.",
      "doc_type": "cases",
      "field": "demographic.days_to_birth",
      "full": "cases.demographic.days_to_birth",
      "type": "long"
    },
    "cases.demographic.days_to_death": {
      "description": "Number of days between the date used for index and the date from a person's date of death represented as a calculated number of days.",
      "doc_type": "cases",
      "field": "demographic.days_to_death",
      "full": "cases.demographic.days_to_death",
      "type": "long"
    },
    "cases.demographic.demographic_id": {
      "description": "",
      "doc_type": "cases",
      "field": "demographic.demographic_id",
      "full": "cases.demographic.demographic_id",
      "type": "keyword"
    },
    "cases.demographic.education_level": {
      "description": "The years of schooling completed in graded public, private, or parochial schools, and in colleges, universities, or professional schools.",
      "doc_type": "cases",
      "field": "demographic.education_level",
      "full": "cases.demographic.education_level",
      "type": "keyword"
    },
    "cases.demographic.ethnicity": {
      "description": "An individual's self-described social and cultural grouping, specifically whether an individual describes themselves as Hispanic or Latino. The provided values are based on the categories defined by the U.S. Office of Management and Business and used by the U.S. Census Bureau.",
      "doc_type": "cases",
      "field": "demographic.ethnicity",
      "full": "cases.demographic.ethnicity",
      "type": "keyword"
    },
    "cases.demographic.gender": {
      "description": "Text designations that identify gender. Gender is described as the assemblage of properties that distinguish people on the basis of their societal roles. [Explanatory Comment 1: Identification of gender is based upon self-report and may come from a form, questionnaire, interview, etc.]",
      "doc_type": "cases",
      "field": "demographic.gender",
      "full": "cases.demographic.gender",
      "type": "keyword"
    },
    "cases.demographic.marital_status": {
      "description": "A demographic parameter indicating a person's current conjugal status.",
      "doc_type": "cases",
      "field": "demographic.marital_status",
      "full": "cases.demographic.marital_status",
      "type": "keyword"
    },
    "cases.demographic.occupation_duration_years": {
      "description": "The number of years a patient worked in a specific occupation.",
      "doc_type": "cases",
      "field": "demographic.occupation_duration_years",
      "full": "cases.demographic.occupation_duration_years",
      "type": "long"
    },
    "cases.demographic.premature_at_birth": {
      "description": "The yes/no/unknown indicator used to describe whether the patient was premature (less than 37 weeks gestation) at birth.",
      "doc_type": "cases",
      "field": "demographic.premature_at_birth",
      "full": "cases.demographic.premature_at_birth",
      "type": "keyword"
    },
    "cases.demographic.race": {
      "description": "An arbitrary classification of a taxonomic group that is a division of a species. It usually arises as a consequence of geographical isolation within a species and is characterized by shared heredity, physical attributes and behavior, and in the case of humans, by common history, nationality, or geographic distribution. The provided values are based on the categories defined by the U.S. Office of Management and Business and used by the U.S. Census Bureau.",
      "doc_type": "cases",
      "field": "demographic.race",
      "full": "cases.demographic.race",
      "type": "keyword"
    },
    "cases.demographic.state": {
      "description": "The current state of the object.",
      "doc_type": "cases",
      "field": "demographic.state",
      "full": "cases.demographic.state",
      "type": "keyword"
    },
    "cases.demographic.submitter_id": {
      "description": "A project-specific identifier for a node. This property is the calling card/nickname/alias for a unit of submission. It can be used in place of the uuid for identifying or recalling a node.",
      "doc_type": "cases",
      "field": "demographic.submitter_id",
      "full": "cases.demographic.submitter_id",
      "type": "keyword"
    },
    "cases.demographic.updated_datetime": {
      "description": "A combination of date and time of day in the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]",
      "doc_type": "cases",
      "field": "demographic.updated_datetime",
      "full": "cases.demographic.updated_datetime",
      "type": "keyword"
    },
    "cases.demographic.vital_status": {
      "description": "The survival state of the person registered on the protocol.",
      "doc_type": "cases",
      "field": "demographic.vital_status",
      "full": "cases.demographic.vital_status",
      "type": "keyword"
    },
    "cases.demographic.weeks_gestation_at_birth": {
      "description": "Numeric value used to describe the number of weeks starting from the approximate date of the biological mother's last menstrual period and ending with the birth of the patient.",
      "doc_type": "cases",
      "field": "demographic.weeks_gestation_at_birth",
      "full": "cases.demographic.weeks_gestation_at_birth",
      "type": "double"
    },
    "cases.demographic.year_of_birth": {
      "description": "Numeric value to represent the calendar year in which an individual was born.",
      "doc_type": "cases",
      "field": "demographic.year_of_birth",
      "full": "cases.demographic.year_of_birth",
      "type": "long"
    },
    "cases.demographic.year_of_death": {
      "description": "Numeric value to represent the year of the death of an individual.",
      "doc_type": "cases",
      "field": "demographic.year_of_death",
      "full": "cases.demographic.year_of_death",
      "type": "long"
    },
    "cases.diagnoses.adrenal_hormone": {
      "description": "Indicates the presence of the adrenal hormone. The adrenal hormone is made from cholesterol and protein produced by the adrenal glands and regulate electrolyte balance, blood pressure, inflammation, blood sugar balance, and immune system control.",
      "doc_type": "cases",
      "field": "diagnoses.adrenal_hormone",
      "full": "cases.diagnoses.adrenal_hormone",
      "type": "keyword"
    },
    "cases.diagnoses.age_at_diagnosis": {
      "description": "Age at the time of diagnosis expressed in number of days since birth.",
      "doc_type": "cases",
      "field": "diagnoses.age_at_diagnosis",
      "full": "cases.diagnoses.age_at_diagnosis",
      "type": "long"
    },
    "cases.diagnoses.ajcc_clinical_m": {
      "description": "Extent of the distant metastasis for the cancer based on evidence obtained from clinical assessment parameters determined prior to treatment.",
      "doc_type": "cases",
      "field": "diagnoses.ajcc_clinical_m",
      "full": "cases.diagnoses.ajcc_clinical_m",
      "type": "keyword"
    },
    "cases.diagnoses.ajcc_clinical_n": {
      "description": "Extent of the regional lymph node involvement for the cancer based on evidence obtained from clinical assessment parameters determined prior to treatment.",
      "doc_type": "cases",
      "field": "diagnoses.ajcc_clinical_n",
      "full": "cases.diagnoses.ajcc_clinical_n",
      "type": "keyword"
    },
    "cases.diagnoses.ajcc_clinical_stage": {
      "description": "Stage group determined from clinical information on the tumor (T), regional node (N) and metastases (M) and by grouping cases with similar prognosis for cancer.",
      "doc_type": "cases",
      "field": "diagnoses.ajcc_clinical_stage",
      "full": "cases.diagnoses.ajcc_clinical_stage",
      "type": "keyword"
    },
    "cases.diagnoses.ajcc_clinical_t": {
      "description": "Extent of the primary cancer based on evidence obtained from clinical assessment parameters determined prior to treatment.",
      "doc_type": "cases",
      "field": "diagnoses.ajcc_clinical_t",
      "full": "cases.diagnoses.ajcc_clinical_t",
      "type": "keyword"
    },
    "cases.diagnoses.ajcc_pathologic_m": {
      "description": "Code to represent the defined absence or presence of distant spread or metastases (M) to locations via vascular channels or lymphatics beyond the regional lymph nodes, using criteria established by the American Joint Committee on Cancer (AJCC).",
      "doc_type": "cases",
      "field": "diagnoses.ajcc_pathologic_m",
      "full": "cases.diagnoses.ajcc_pathologic_m",
      "type": "keyword"
    },
    "cases.diagnoses.ajcc_pathologic_n": {
      "description": "The codes that represent the stage of cancer based on the nodes present (N stage) according to criteria based on multiple editions of the AJCC's Cancer Staging Manual.",
      "doc_type": "cases",
      "field": "diagnoses.ajcc_pathologic_n",
      "full": "cases.diagnoses.ajcc_pathologic_n",
      "type": "keyword"
    },
    "cases.diagnoses.ajcc_pathologic_stage": {
      "description": "The extent of a cancer, especially whether the disease has spread from the original site to other parts of the body based on AJCC staging criteria.",
      "doc_type": "cases",
      "field": "diagnoses.ajcc_pathologic_stage",
      "full": "cases.diagnoses.ajcc_pathologic_stage",
      "type": "keyword"
    },
    "cases.diagnoses.ajcc_pathologic_t": {
      "description": "Code of pathological T (primary tumor) to define the size or contiguous extension of the primary tumor (T), using staging criteria from the American Joint Committee on Cancer (AJCC).",
      "doc_type": "cases",
      "field": "diagnoses.ajcc_pathologic_t",
      "full": "cases.diagnoses.ajcc_pathologic_t",
      "type": "keyword"
    },
    "cases.diagnoses.ajcc_staging_system_edition": {
      "description": "The text term used to describe the version or edition of the American Joint Committee on Cancer Staging Handbooks, a publication by the group formed for the purpose of developing a system of staging for cancer that is acceptable to the American medical profession and is compatible with other accepted classifications.",
      "doc_type": "cases",
      "field": "diagnoses.ajcc_staging_system_edition",
      "full": "cases.diagnoses.ajcc_staging_system_edition",
      "type": "keyword"
    },
    "cases.diagnoses.anaplasia_present": {
      "description": "",
      "doc_type": "cases",
      "field": "diagnoses.anaplasia_present",
      "full": "cases.diagnoses.anaplasia_present",
      "type": "keyword"
    },
    "cases.diagnoses.anaplasia_present_type": {
      "description": "",
      "doc_type": "cases",
      "field": "diagnoses.anaplasia_present_type",
      "full": "cases.diagnoses.anaplasia_present_type",
      "type": "keyword"
    },
    "cases.diagnoses.ann_arbor_b_symptoms": {
      "description": "Text term to signify whether lymphoma B-symptoms are present as noted in the patient's medical record.",
      "doc_type": "cases",
      "field": "diagnoses.ann_arbor_b_symptoms",
      "full": "cases.diagnoses.ann_arbor_b_symptoms",
      "type": "keyword"
    },
    "cases.diagnoses.ann_arbor_b_symptoms_described": {
      "description": "Text describing the specific lymphoma B-symptoms present.",
      "doc_type": "cases",
      "field": "diagnoses.ann_arbor_b_symptoms_described",
      "full": "cases.diagnoses.ann_arbor_b_symptoms_described",
      "type": "keyword"
    },
    "cases.diagnoses.ann_arbor_clinical_stage": {

In [8]:
# Campos de interesse para a requisição ao endpoint
fields = [
    'case_id',
    'disease_type',
    'files.access',
    'files.data_category',
    'files.data_format',
    'files.data_type',
    'files.file_id',
    'files.experimental_strategy',
    'files.state_comment',
    'primary_site',
    'project.project_id',
    'state'
]
fields = ','.join(fields)

# Parâmetros para a requisição ao endpoint
params = {
    'fields': fields,
    'format': 'json'
}

# Busca por um dos objetos da API
response = requests.post(
    url=CASES_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields, 'size': '1'}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Printa um dos objetos do conteúdo da resposta
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

[
  {
    "id": "69eced5b-1e76-45c9-bc9c-2aa71a921c57",
    "primary_site": "Brain",
    "disease_type": "Gliomas",
    "case_id": "69eced5b-1e76-45c9-bc9c-2aa71a921c57",
    "project": {
      "project_id": "HCMI-CMDC"
    },
    "files": [
      {
        "data_format": "MAF",
        "access": "open",
        "file_id": "e630f1fa-d0c2-4a6b-9cb5-fd7c3ca697e6",
        "data_type": "Masked Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "1c062307-bff0-4586-a945-f9d192906f29",
        "data_type": "Splice Junction Quantification",
        "data_category": "Transcriptome Profiling",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "SVS",
        "access": "open",
        "file_id": "5d1b35ab-0550-4d8e-8097-6daa2814ec22",
        "data_type": "Slide Image",
        "data_category": "Biospecimen",
        "experimental_strategy": "Tissue Slide"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "daf31248-9fd5-4dd7-82c1-eb1240dcef96",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "CDC JSON",
        "access": "open",
        "file_id": "760875d1-8992-4231-a681-b71dc8759467",
        "data_type": "Clinical Supplement",
        "data_category": "Clinical"
      },
      {
        "data_format": "TXT",
        "access": "open",
        "file_id": "7913424e-08b7-4063-87be-4090b425d81b",
        "data_type": "Methylation Beta Value",
        "data_category": "DNA Methylation",
        "experimental_strategy": "Methylation Array"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "205d013e-1d17-4bfb-8679-f23427b10560",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "bfa46875-3062-4327-b32a-30fa3ade91cf",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "BEDPE",
        "access": "controlled",
        "file_id": "45867207-3cd1-47b1-baed-bb5c02cf11f6",
        "data_type": "Structural Rearrangement",
        "data_category": "Somatic Structural Variation",
        "experimental_strategy": "WGS"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "f5a60cb8-2af4-43eb-b8ad-c3856f97a8fc",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "b8b25090-795c-4785-815c-99bead8846cd",
        "data_type": "Structural Rearrangement",
        "data_category": "Somatic Structural Variation",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "5cda0751-c3f6-4087-9aec-e0f96f51717c",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "BEDPE",
        "access": "controlled",
        "file_id": "b191750f-3708-46cc-930f-069de984fde7",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "b3edf5d0-8690-4f68-b4fc-3ae74bc9f66f",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "82779483-d87a-4a97-8c67-844884da3208",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "4926c198-97bb-4196-9cf0-1cea97a9257d",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "cbcfbded-90f4-4473-aeff-4d616202044b",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "a4a705bc-cb1c-4eef-9f32-9ba04ed49fd8",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "TSV",
        "access": "open",
        "file_id": "4909ea2e-8823-45c7-acfd-9b2504cc8731",
        "data_type": "Gene Expression Quantification",
        "data_category": "Transcriptome Profiling",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BEDPE",
        "access": "controlled",
        "file_id": "88329199-260b-4b16-a65d-0656e646c4d5",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "MAF",
        "access": "controlled",
        "file_id": "1f9fb144-9820-4a05-8826-f376dbb97111",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "b5b4dac9-8bfe-46b1-9f36-b736fc5daece",
        "data_type": "Structural Rearrangement",
        "data_category": "Somatic Structural Variation",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "0b0cfd0f-1c63-48dc-ac95-9469fd26328a",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "1ce992bd-56f5-45ab-ac87-35a317161319",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "ce610598-d477-4f5b-bbde-d5823adf5f93",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "BCR XML",
        "access": "open",
        "file_id": "013b8dbb-49ad-4a41-ab05-16c42f64fdd6",
        "data_type": "Biospecimen Supplement",
        "data_category": "Biospecimen"
      },
      {
        "data_format": "MAF",
        "access": "controlled",
        "file_id": "0c900c7a-9da0-4a68-9444-81d9dccc77b4",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "TSV",
        "access": "open",
        "file_id": "9c4ba807-ce7d-4f9c-b6da-50b266303612",
        "data_type": "Gene Expression Quantification",
        "data_category": "Transcriptome Profiling",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BEDPE",
        "access": "controlled",
        "file_id": "44d9768b-fbdd-4cc7-b2d3-37ece075c959",
        "data_type": "Structural Rearrangement",
        "data_category": "Somatic Structural Variation",
        "experimental_strategy": "WGS"
      },
      {
        "data_format": "MAF",
        "access": "controlled",
        "file_id": "0ace8922-9c14-4bbd-ab93-0b37c7a22893",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "f4902a20-fc37-4a47-88da-5c2304f8c548",
        "data_type": "Splice Junction Quantification",
        "data_category": "Transcriptome Profiling",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BEDPE",
        "access": "controlled",
        "file_id": "836fe038-9f41-40c6-ba60-14d75f7e368b",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "MAF",
        "access": "controlled",
        "file_id": "55b624d6-f438-4383-8d68-6203ac96c2ca",
        "data_type": "Aggregated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "59156041-3d74-40f9-a0a0-d725cefef07f",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BEDPE",
        "access": "controlled",
        "file_id": "e3617d8a-9203-413a-a5dc-bf82beb9ee9b",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "1f1745db-d88a-47c5-b8ef-832302557271",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "7be4ce37-deeb-4dbc-bb4d-23c100fcc57a",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "MAF",
        "access": "controlled",
        "file_id": "17fa71fc-b504-45b5-b1c6-dd292006fbe6",
        "data_type": "Aggregated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "fdef9ec2-7021-4c97-bdfb-ada89cdaf979",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "ed15b997-2fbb-4945-97ff-488060ffa720",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "1b9d2d0d-b1b8-4dce-b2c5-2196098c10e4",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "TXT",
        "access": "open",
        "file_id": "71dfa20d-9735-4a71-84e9-adec4558c7ec",
        "data_type": "Copy Number Segment",
        "data_category": "Copy Number Variation",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "IDAT",
        "access": "open",
        "file_id": "acc5a60b-ca92-4aaf-8a77-b35e395d38f1",
        "data_type": "Masked Intensities",
        "data_category": "DNA Methylation",
        "experimental_strategy": "Methylation Array"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "e0311fe5-244a-49be-8409-ac37fc3743d6",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "MAF",
        "access": "controlled",
        "file_id": "8270bbfd-8621-4bb4-b8bb-fde81092f66c",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "aaacfb1b-c2ce-4d51-9cff-0fca3f0115f2",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "591516cc-89b9-4c07-b0bf-ec47ff688d9d",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "029d638a-01cd-4a26-90f9-0bcdbe44124d",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "a85bcc41-aacf-4b49-85bf-08f858ab94e0",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "42e9d0d3-7707-4d8d-993f-558ad648427a",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "c063012a-d045-424c-a916-64a8b24a337b",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "5d7ae703-8470-476a-a161-e7ad9a53be4e",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "TXT",
        "access": "open",
        "file_id": "48a2f4f1-9da4-485f-b893-de35035121e1",
        "data_type": "Copy Number Segment",
        "data_category": "Copy Number Variation",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "e5ba52e5-0fd4-46cd-9f51-1117e9417d18",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "591dd431-8a43-4482-aadd-7941678ddc5a",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "933e4008-c5a0-4ef2-9c28-639fad33d40d",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "TSV",
        "access": "open",
        "file_id": "64eb998e-97ea-46b4-86eb-1c79b0587a15",
        "data_type": "Gene Level Copy Number",
        "data_category": "Copy Number Variation",
        "experimental_strategy": "WGS"
      },
      {
        "data_format": "MAF",
        "access": "controlled",
        "file_id": "b805eb18-b3ba-4e27-bccf-d7d09f37772a",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "MAF",
        "access": "controlled",
        "file_id": "1d2754b3-0671-4566-a499-e59194de77d8",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "7dbc20ba-331b-44c1-b6cc-cdf5c7e47272",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS",
        "state_comment": null
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "179ef928-eed6-4a72-abae-8860d0c1aab3",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "SVS",
        "access": "open",
        "file_id": "8c6e717d-815c-408d-8390-b745db03be08",
        "data_type": "Slide Image",
        "data_category": "Biospecimen",
        "experimental_strategy": "Tissue Slide"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "9da141c1-a925-4b9b-a8c8-b8d38ecd4a99",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "TSV",
        "access": "open",
        "file_id": "cdbc0f7a-550c-4a99-8987-3d8cdb338ee1",
        "data_type": "Gene Level Copy Number",
        "data_category": "Copy Number Variation",
        "experimental_strategy": "WGS"
      },
      {
        "data_format": "MAF",
        "access": "controlled",
        "file_id": "ad959d9a-4371-4e12-a5d3-15daeb04c3da",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "5bb98935-450d-4c15-84de-0c5d8dfd2470",
        "data_type": "Annotated Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "MAF",
        "access": "open",
        "file_id": "d8c59308-850c-4169-b014-1d9e9befed40",
        "data_type": "Masked Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WXS"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "4cd51956-9e68-41ba-acb0-3dadeab3d8b1",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "VCF",
        "access": "controlled",
        "file_id": "bc753b65-3716-4845-802b-6b28dfa3ef1f",
        "data_type": "Raw Simple Somatic Mutation",
        "data_category": "Simple Nucleotide Variation",
        "experimental_strategy": "WGS",
        "state_comment": null
      },
      {
        "data_format": "IDAT",
        "access": "open",

## `files`

In [9]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{FILES_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON e a printa
json_response = json.loads(response.content.decode('utf-8'))
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

{
  "_mapping": {
    "files.access": {
      "description": "",
      "doc_type": "files",
      "field": "access",
      "full": "files.access",
      "type": "keyword"
    },
    "files.acl": {
      "description": "",
      "doc_type": "files",
      "field": "acl",
      "full": "files.acl",
      "type": "keyword"
    },
    "files.analysis.analysis_id": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.analysis_id",
      "full": "files.analysis.analysis_id",
      "type": "keyword"
    },
    "files.analysis.analysis_type": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.analysis_type",
      "full": "files.analysis.analysis_type",
      "type": "keyword"
    },
    "files.analysis.created_datetime": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.created_datetime",
      "full": "files.analysis.created_datetime",
      "type": "keyword"
    },
    "files.analysis.input_files.access": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.access",
      "full": "files.analysis.input_files.access",
      "type": "keyword"
    },
    "files.analysis.input_files.average_base_quality": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.average_base_quality",
      "full": "files.analysis.input_files.average_base_quality",
      "type": "double"
    },
    "files.analysis.input_files.average_insert_size": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.average_insert_size",
      "full": "files.analysis.input_files.average_insert_size",
      "type": "long"
    },
    "files.analysis.input_files.average_read_length": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.average_read_length",
      "full": "files.analysis.input_files.average_read_length",
      "type": "long"
    },
    "files.analysis.input_files.cancer_dna_fraction": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.cancer_dna_fraction",
      "full": "files.analysis.input_files.cancer_dna_fraction",
      "type": "double"
    },
    "files.analysis.input_files.channel": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.channel",
      "full": "files.analysis.input_files.channel",
      "type": "keyword"
    },
    "files.analysis.input_files.chip_id": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.chip_id",
      "full": "files.analysis.input_files.chip_id",
      "type": "keyword"
    },
    "files.analysis.input_files.chip_position": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.chip_position",
      "full": "files.analysis.input_files.chip_position",
      "type": "keyword"
    },
    "files.analysis.input_files.contamination": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.contamination",
      "full": "files.analysis.input_files.contamination",
      "type": "double"
    },
    "files.analysis.input_files.contamination_error": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.contamination_error",
      "full": "files.analysis.input_files.contamination_error",
      "type": "double"
    },
    "files.analysis.input_files.created_datetime": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.created_datetime",
      "full": "files.analysis.input_files.created_datetime",
      "type": "keyword"
    },
    "files.analysis.input_files.data_category": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.data_category",
      "full": "files.analysis.input_files.data_category",
      "type": "keyword"
    },
    "files.analysis.input_files.data_format": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.data_format",
      "full": "files.analysis.input_files.data_format",
      "type": "keyword"
    },
    "files.analysis.input_files.data_type": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.data_type",
      "full": "files.analysis.input_files.data_type",
      "type": "keyword"
    },
    "files.analysis.input_files.error_type": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.error_type",
      "full": "files.analysis.input_files.error_type",
      "type": "keyword"
    },
    "files.analysis.input_files.experimental_strategy": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.experimental_strategy",
      "full": "files.analysis.input_files.experimental_strategy",
      "type": "keyword"
    },
    "files.analysis.input_files.file_id": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.file_id",
      "full": "files.analysis.input_files.file_id",
      "type": "keyword"
    },
    "files.analysis.input_files.file_name": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.file_name",
      "full": "files.analysis.input_files.file_name",
      "type": "keyword"
    },
    "files.analysis.input_files.file_size": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.file_size",
      "full": "files.analysis.input_files.file_size",
      "type": "long"
    },
    "files.analysis.input_files.genome_doubling": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.genome_doubling",
      "full": "files.analysis.input_files.genome_doubling",
      "type": "long"
    },
    "files.analysis.input_files.imaging_date": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.imaging_date",
      "full": "files.analysis.input_files.imaging_date",
      "type": "keyword"
    },
    "files.analysis.input_files.magnification": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.magnification",
      "full": "files.analysis.input_files.magnification",
      "type": "double"
    },
    "files.analysis.input_files.md5sum": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.md5sum",
      "full": "files.analysis.input_files.md5sum",
      "type": "keyword"
    },
    "files.analysis.input_files.mean_coverage": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.mean_coverage",
      "full": "files.analysis.input_files.mean_coverage",
      "type": "double"
    },
    "files.analysis.input_files.msi_score": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.msi_score",
      "full": "files.analysis.input_files.msi_score",
      "type": "double"
    },
    "files.analysis.input_files.msi_status": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.msi_status",
      "full": "files.analysis.input_files.msi_status",
      "type": "keyword"
    },
    "files.analysis.input_files.pairs_on_diff_chr": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.pairs_on_diff_chr",
      "full": "files.analysis.input_files.pairs_on_diff_chr",
      "type": "long"
    },
    "files.analysis.input_files.plate_name": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.plate_name",
      "full": "files.analysis.input_files.plate_name",
      "type": "keyword"
    },
    "files.analysis.input_files.plate_well": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.plate_well",
      "full": "files.analysis.input_files.plate_well",
      "type": "keyword"
    },
    "files.analysis.input_files.platform": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.platform",
      "full": "files.analysis.input_files.platform",
      "type": "keyword"
    },
    "files.analysis.input_files.proc_internal": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.proc_internal",
      "full": "files.analysis.input_files.proc_internal",
      "type": "keyword"
    },
    "files.analysis.input_files.proportion_base_mismatch": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.proportion_base_mismatch",
      "full": "files.analysis.input_files.proportion_base_mismatch",
      "type": "double"
    },
    "files.analysis.input_files.proportion_coverage_10X": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.proportion_coverage_10X",
      "full": "files.analysis.input_files.proportion_coverage_10X",
      "type": "double"
    },
    "files.analysis.input_files.proportion_coverage_10x": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.proportion_coverage_10x",
      "full": "files.analysis.input_files.proportion_coverage_10x",
      "type": "double"
    },
    "files.analysis.input_files.proportion_coverage_30X": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.proportion_coverage_30X",
      "full": "files.analysis.input_files.proportion_coverage_30X",
      "type": "double"
    },
    "files.analysis.input_files.proportion_coverage_30x": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.proportion_coverage_30x",
      "full": "files.analysis.input_files.proportion_coverage_30x",
      "type": "double"
    },
    "files.analysis.input_files.proportion_reads_duplicated": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.proportion_reads_duplicated",
      "full": "files.analysis.input_files.proportion_reads_duplicated",
      "type": "double"
    },
    "files.analysis.input_files.proportion_reads_mapped": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.proportion_reads_mapped",
      "full": "files.analysis.input_files.proportion_reads_mapped",
      "type": "double"
    },
    "files.analysis.input_files.proportion_targets_no_coverage": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.proportion_targets_no_coverage",
      "full": "files.analysis.input_files.proportion_targets_no_coverage",
      "type": "double"
    },
    "files.analysis.input_files.read_pair_number": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.read_pair_number",
      "full": "files.analysis.input_files.read_pair_number",
      "type": "keyword"
    },
    "files.analysis.input_files.revision": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.revision",
      "full": "files.analysis.input_files.revision",
      "type": "double"
    },
    "files.analysis.input_files.stain_type": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.stain_type",
      "full": "files.analysis.input_files.stain_type",
      "type": "keyword"
    },
    "files.analysis.input_files.state": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.state",
      "full": "files.analysis.input_files.state",
      "type": "keyword"
    },
    "files.analysis.input_files.state_comment": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.state_comment",
      "full": "files.analysis.input_files.state_comment",
      "type": "keyword"
    },
    "files.analysis.input_files.subclonal_genome_fraction": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.subclonal_genome_fraction",
      "full": "files.analysis.input_files.subclonal_genome_fraction",
      "type": "double"
    },
    "files.analysis.input_files.submitter_id": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.submitter_id",
      "full": "files.analysis.input_files.submitter_id",
      "type": "keyword"
    },
    "files.analysis.input_files.total_reads": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.total_reads",
      "full": "files.analysis.input_files.total_reads",
      "type": "long"
    },
    "files.analysis.input_files.tumor_ploidy": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.tumor_ploidy",
      "full": "files.analysis.input_files.tumor_ploidy",
      "type": "double"
    },
    "files.analysis.input_files.tumor_purity": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.tumor_purity",
      "full": "files.analysis.input_files.tumor_purity",
      "type": "double"
    },
    "files.analysis.input_files.updated_datetime": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.updated_datetime",
      "full": "files.analysis.input_files.updated_datetime",
      "type": "keyword"
    },
    "files.analysis.input_files.wgs_coverage": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.input_files.wgs_coverage",
      "full": "files.analysis.input_files.wgs_coverage",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.RIN": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.RIN",
      "full": "files.analysis.metadata.read_groups.RIN",
      "type": "double"
    },
    "files.analysis.metadata.read_groups.adapter_name": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.adapter_name",
      "full": "files.analysis.metadata.read_groups.adapter_name",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.adapter_sequence": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.adapter_sequence",
      "full": "files.analysis.metadata.read_groups.adapter_sequence",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.base_caller_name": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.base_caller_name",
      "full": "files.analysis.metadata.read_groups.base_caller_name",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.base_caller_version": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.base_caller_version",
      "full": "files.analysis.metadata.read_groups.base_caller_version",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.chipseq_antibody": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.chipseq_antibody",
      "full": "files.analysis.metadata.read_groups.chipseq_antibody",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.chipseq_target": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.chipseq_target",
      "full": "files.analysis.metadata.read_groups.chipseq_target",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.created_datetime": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.created_datetime",
      "full": "files.analysis.metadata.read_groups.created_datetime",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.days_to_sequencing": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.days_to_sequencing",
      "full": "files.analysis.metadata.read_groups.days_to_sequencing",
      "type": "long"
    },
    "files.analysis.metadata.read_groups.experiment_name": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.experiment_name",
      "full": "files.analysis.metadata.read_groups.experiment_name",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.flow_cell_barcode": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.flow_cell_barcode",
      "full": "files.analysis.metadata.read_groups.flow_cell_barcode",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.fragment_maximum_length": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.fragment_maximum_length",
      "full": "files.analysis.metadata.read_groups.fragment_maximum_length",
      "type": "long"
    },
    "files.analysis.metadata.read_groups.fragment_mean_length": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.fragment_mean_length",
      "full": "files.analysis.metadata.read_groups.fragment_mean_length",
      "type": "double"
    },
    "files.analysis.metadata.read_groups.fragment_minimum_length": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.fragment_minimum_length",
      "full": "files.analysis.metadata.read_groups.fragment_minimum_length",
      "type": "long"
    },
    "files.analysis.metadata.read_groups.fragment_standard_deviation_length": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.fragment_standard_deviation_length",
      "full": "files.analysis.metadata.read_groups.fragment_standard_deviation_length",
      "type": "double"
    },
    "files.analysis.metadata.read_groups.fragmentation_enzyme": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.fragmentation_enzyme",
      "full": "files.analysis.metadata.read_groups.fragmentation_enzyme",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.includes_spike_ins": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.includes_spike_ins",
      "full": "files.analysis.metadata.read_groups.includes_spike_ins",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.instrument_model": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.instrument_model",
      "full": "files.analysis.metadata.read_groups.instrument_model",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.is_paired_end": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.is_paired_end",
      "full": "files.analysis.metadata.read_groups.is_paired_end",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.lane_number": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.lane_number",
      "full": "files.analysis.metadata.read_groups.lane_number",
      "type": "long"
    },
    "files.analysis.metadata.read_groups.library_name": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.library_name",
      "full": "files.analysis.metadata.read_groups.library_name",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.library_preparation_kit_catalog_number": {
      "description": "",
      "doc_type": "files",
      "field": "analysis.metadata.read_groups.library_preparation_kit_catalog_number",
      "full": "files.analysis.metadata.read_groups.library_preparation_kit_catalog_number",
      "type": "keyword"
    },
    "files.analysis.metadata.read_groups.library_preparation_kit_name": {
      "description": "",
      "doc_type": "files",

In [10]:
# Campos de interesse para a requisição ao endpoint
fields = [
    'access',
    'cases.case_id',
    'contamination',
    'contamination_error',
    'data_category',
    'data_format',
    'data_type',
    'error_type',
    'experimental_strategy',
    'file_id',
    'file_name',
    'file_size',
    'state'
]
fields = ','.join(fields)

# Parâmetros para a requisição ao endpoint
params = {
    'fields': fields,
    'format': 'json'
}

# Busca por um dos objetos API
response = requests.post(
    url=FILES_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields, 'size': '1'}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Printa um dos objetos do conteúdo da resposta
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

[
  {
    "id": "593eee9b-bd8e-4672-aed4-24d406b257fa",
    "data_format": "VCF",
    "cases": [
      {
        "case_id": "273266ae-2ab9-59c7-836f-84281b1d12e7"
      }
    ],
    "access": "controlled",
    "file_name": "TARGET-NBL.4c06f97e-f54b-4b03-8bc7-869619e09e98.targeted_sequencing.muse.raw_somatic_mutation.vcf.gz",
    "file_id": "593eee9b-bd8e-4672-aed4-24d406b257fa",
    "data_type": "Raw Simple Somatic Mutation",
    "data_category": "Simple Nucleotide Variation",
    "state": "released",
    "experimental_strategy": "Targeted Sequencing",
    "file_size": 18320
  }
]

## `annotations`

In [11]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{ANNOTATIONS_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON e a printa
json_response = json.loads(response.content.decode('utf-8'))
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

{
  "_mapping": {
    "annotations.annotation_autocomplete": {
      "description": "",
      "doc_type": "annotations",
      "field": "annotation_autocomplete",
      "full": "annotations.annotation_autocomplete",
      "type": "id"
    },
    "annotations.annotation_id": {
      "description": "",
      "doc_type": "annotations",
      "field": "annotation_id",
      "full": "annotations.annotation_id",
      "type": "keyword"
    },
    "annotations.case_id": {
      "description": "",
      "doc_type": "annotations",
      "field": "case_id",
      "full": "annotations.case_id",
      "type": "keyword"
    },
    "annotations.case_submitter_id": {
      "description": "",
      "doc_type": "annotations",
      "field": "case_submitter_id",
      "full": "annotations.case_submitter_id",
      "type": "keyword"
    },
    "annotations.category": {
      "description": "",
      "doc_type": "annotations",
      "field": "category",
      "full": "annotations.category",
      "type": "keyword"
    },
    "annotations.classification": {
      "description": "",
      "doc_type": "annotations",
      "field": "classification",
      "full": "annotations.classification",
      "type": "keyword"
    },
    "annotations.created_datetime": {
      "description": "",
      "doc_type": "annotations",
      "field": "created_datetime",
      "full": "annotations.created_datetime",
      "type": "keyword"
    },
    "annotations.entity_id": {
      "description": "",
      "doc_type": "annotations",
      "field": "entity_id",
      "full": "annotations.entity_id",
      "type": "keyword"
    },
    "annotations.entity_submitter_id": {
      "description": "",
      "doc_type": "annotations",
      "field": "entity_submitter_id",
      "full": "annotations.entity_submitter_id",
      "type": "keyword"
    },
    "annotations.entity_type": {
      "description": "",
      "doc_type": "annotations",
      "field": "entity_type",
      "full": "annotations.entity_type",
      "type": "keyword"
    },
    "annotations.legacy_created_datetime": {
      "description": "",
      "doc_type": "annotations",
      "field": "legacy_created_datetime",
      "full": "annotations.legacy_created_datetime",
      "type": "keyword"
    },
    "annotations.legacy_updated_datetime": {
      "description": "",
      "doc_type": "annotations",
      "field": "legacy_updated_datetime",
      "full": "annotations.legacy_updated_datetime",
      "type": "keyword"
    },
    "annotations.notes": {
      "description": "",
      "doc_type": "annotations",
      "field": "notes",
      "full": "annotations.notes",
      "type": "keyword"
    },
    "annotations.project.code": {
      "description": "Project code",
      "doc_type": "annotations",
      "field": "project.code",
      "full": "annotations.project.code",
      "type": "keyword"
    },
    "annotations.project.dbgap_accession_number": {
      "description": "The dbgap accession number for the project.",
      "doc_type": "annotations",
      "field": "project.dbgap_accession_number",
      "full": "annotations.project.dbgap_accession_number",
      "type": "keyword"
    },
    "annotations.project.disease_type": {
      "description": "Full name for the project",
      "doc_type": "annotations",
      "field": "project.disease_type",
      "full": "annotations.project.disease_type",
      "type": "keyword"
    },
    "annotations.project.intended_release_date": {
      "description": "Tracks a Project's intended release date.",
      "doc_type": "annotations",
      "field": "project.intended_release_date",
      "full": "annotations.project.intended_release_date",
      "type": "keyword"
    },
    "annotations.project.name": {
      "description": "Display name for the project",
      "doc_type": "annotations",
      "field": "project.name",
      "full": "annotations.project.name",
      "type": "keyword"
    },
    "annotations.project.primary_site": {
      "description": "Primary site for the project",
      "doc_type": "annotations",
      "field": "project.primary_site",
      "full": "annotations.project.primary_site",
      "type": "keyword"
    },
    "annotations.project.program.dbgap_accession_number": {
      "description": "The dbgap accession number provided for the program.",
      "doc_type": "annotations",
      "field": "project.program.dbgap_accession_number",
      "full": "annotations.project.program.dbgap_accession_number",
      "type": "keyword"
    },
    "annotations.project.program.name": {
      "description": "Full name/title of the program.",
      "doc_type": "annotations",
      "field": "project.program.name",
      "full": "annotations.project.program.name",
      "type": "keyword"
    },
    "annotations.project.program.program_id": {
      "description": "",
      "doc_type": "annotations",
      "field": "project.program.program_id",
      "full": "annotations.project.program.program_id",
      "type": "keyword"
    },
    "annotations.project.project_id": {
      "description": "",
      "doc_type": "annotations",
      "field": "project.project_id",
      "full": "annotations.project.project_id",
      "type": "keyword"
    },
    "annotations.project.releasable": {
      "description": "A project can only be released by the user when `releasable` is true.",
      "doc_type": "annotations",
      "field": "project.releasable",
      "full": "annotations.project.releasable",
      "type": "keyword"
    },
    "annotations.project.released": {
      "description": "To release a project is to tell the GDC to include all submitted entities in the next GDC index.",
      "doc_type": "annotations",
      "field": "project.released",
      "full": "annotations.project.released",
      "type": "keyword"
    },
    "annotations.project.state": {
      "description": "The possible states a project can be in.  All but `open` are equivalent to some type of locked state.",
      "doc_type": "annotations",
      "field": "project.state",
      "full": "annotations.project.state",
      "type": "keyword"
    },
    "annotations.state": {
      "description": "",
      "doc_type": "annotations",
      "field": "state",
      "full": "annotations.state",
      "type": "keyword"
    },
    "annotations.status": {
      "description": "",
      "doc_type": "annotations",
      "field": "status",
      "full": "annotations.status",
      "type": "keyword"
    },
    "annotations.submitter_id": {
      "description": "",
      "doc_type": "annotations",
      "field": "submitter_id",
      "full": "annotations.submitter_id",
      "type": "keyword"
    },
    "annotations.updated_datetime": {
      "description": "",
      "doc_type": "annotations",
      "field": "updated_datetime",
      "full": "annotations.updated_datetime",
      "type": "keyword"
    }
  },
  "defaults": [
    "annotation_autocomplete",
    "annotation_id",
    "case_id",
    "case_submitter_id",
    "category",
    "classification",
    "created_datetime",
    "entity_id",
    "entity_submitter_id",
    "entity_type",
    "legacy_created_datetime",
    "legacy_updated_datetime",
    "notes",
    "state",
    "status",
    "submitter_id",
    "updated_datetime"
  ],
  "expand": [
    "project",
    "project.program"
  ],
  "fields": [
    "annotation_autocomplete",
    "annotation_id",
    "case_id",
    "case_submitter_id",
    "category",
    "classification",
    "created_datetime",
    "entity_id",
    "entity_submitter_id",
    "entity_type",
    "legacy_created_datetime",
    "legacy_updated_datetime",
    "notes",
    "project.code",
    "project.dbgap_accession_number",
    "project.disease_type",
    "project.intended_release_date",
    "project.name",
    "project.primary_site",
    "project.program.dbgap_accession_number",
    "project.program.name",
    "project.program.program_id",
    "project.project_id",
    "project.releasable",
    "project.released",
    "project.state",
    "state",
    "status",
    "submitter_id",
    "updated_datetime"
  ],
  "multi": [],
  "nested": []
}

In [12]:
# Campos disponíveis no endpoint
fields = [
    'annotation_autocomplete',
    'annotation_id',
    'case_id',
    'case_submitter_id',
    'category',
    'classification',
    'created_datetime',
    'entity_id',
    'entity_submitter_id',
    'entity_type',
    'legacy_created_datetime',
    'legacy_updated_datetime',
    'notes',
    'project.code',
    'project.dbgap_accession_number',
    'project.disease_type',
    'project.intended_release_date',
    'project.name',
    'project.primary_site',
    'project.program.dbgap_accession_number',
    'project.program.name',
    'project.program.program_id',
    'project.project_id',
    'project.releasable',
    'project.released',
    'project.state',
    'state',
    'status',
    'submitter_id',
    'updated_datetime'
]
fields = ','.join(fields)

# Busca por um dos objetos da API
response = requests.post(
    url=ANNOTATIONS_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields, 'size': '1'}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Printa um dos objetos do conteúdo da resposta
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

[
  {
    "id": "56df671a-c3af-4daa-bc9f-4b131831b044",
    "entity_submitter_id": "HCM-BROD-0005-C41",
    "notes": "The GDC received notice on July 27 2021 that the case's molecular data failed quality checks at submitter institution, and thus will need to be redacted until new data is submitted. Please see JIRA ticket DAT-3087 for more information.",
    "project": {
      "primary_site": [
        "Connective, subcutaneous and other soft tissues",
        "Other and unspecified parts of tongue",
        "Other and unspecified parts of biliary tract",
        "Other and unspecified parts of mouth",
        "Rectum",
        "Uterus, NOS",
        "Pancreas",
        "Corpus uteri",
        "Other and ill-defined sites",
        "Gallbladder",
        "Breast",
        "Kidney",
        "Nasal cavity and middle ear",
        "Liver and intrahepatic bile ducts",
        "Rectosigmoid junction",
        "Stomach",
        "Bronchus and lung",
        "Colon",
        "Ovary",
        "Bones, joints and articular cartilage of other and unspecified sites",
        "Skin",
        "Small intestine",
        "Esophagus",
        "Brain"
      ],
      "dbgap_accession_number": null,
      "project_id": "HCMI-CMDC",
      "disease_type": [
        "Complex Mixed and Stromal Neoplasms",
        "Acinar Cell Neoplasms",
        "Adenomas and Adenocarcinomas",
        "Squamous Cell Neoplasms",
        "Gliomas",
        "Fibromatous Neoplasms",
        "Soft Tissue Tumors and Sarcomas, NOS",
        "Myomatous Neoplasms",
        "Blood Vessel Tumors",
        "Osseous and Chondromatous Neoplasms",
        "Ductal and Lobular Neoplasms",
        "Cystic, Mucinous and Serous Neoplasms",
        "Miscellaneous Bone Tumors",
        "Nevi and Melanomas",
        "Complex Epithelial Neoplasms",
        "Epithelial Neoplasms, NOS"
      ],
      "name": "NCI Cancer Model Development for the Human Cancer Model Initiative",
      "releasable": true,
      "state": "open",
      "program": {
        "dbgap_accession_number": "phs001486",
        "program_id": "a5448c11-d46a-56aa-a5e1-5c1aa06404df",
        "name": "HCMI"
      },
      "released": true
    },
    "classification": "Redaction",
    "entity_id": "ddf7c939-5278-4034-b861-36717e11695d",
    "created_datetime": "2021-08-12T14:48:08.817916-05:00",
    "annotation_id": "56df671a-c3af-4daa-bc9f-4b131831b044",
    "entity_type": "case",
    "updated_datetime": "2021-08-12T14:48:08.817916-05:00",
    "case_id": "ddf7c939-5278-4034-b861-36717e11695d",
    "state": "released",
    "category": "General",
    "status": "Approved",
    "case_submitter_id": "HCM-BROD-0005-C41"
  }
]

## `data`

In [13]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{DATA_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON e a printa
json_response = json.loads(response.content.decode('utf-8'))
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

{
  "message": "_mapping not found"
}

# Queries Iniciais

# Total de Projetos

In [14]:
# Campos de interesse no endpoint
fields = [
    'disease_type',
    'name',
    'primary_site',
    'releasable',
    'released',
    'state',
    'summary.experimental_strategies.case_count',
    'summary.experimental_strategies.experimental_strategy',
    'summary.experimental_strategies.file_count',
]
fields = ','.join(fields)

# Busca por todos os objetos da API
response = requests.post(
    url=PROJECTS_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Transforma os valores booleanos em strings
for index in range(len(json_response)):
    obj = json_response[index]
    for key in obj:
        if isinstance(obj[key], bool): 
            obj[key] = str(obj[key])

# Converte o JSON para um DataFrame pandas
df_projects = pd.json_normalize(json_response)

# Printa o DataFrame completo
pd.set_option('display.max_colwidth', 1000)
df_projects

,id,primary_site,disease_type,name,releasable,state,released,summary.experimental_strategies
0,HCMI-CMDC,"[Connective, subcutaneous and other soft tissues, Other and unspecified parts of tongue, Other and unspecified parts of biliary tract, Other and unspecified parts of mouth, Rectum, Uterus, NOS, Pancreas, Corpus uteri, Other and ill-defined sites, Gallbladder, Breast, Kidney, Nasal cavity and middle ear, Liver and intrahepatic bile ducts, Rectosigmoid junction, Stomach, Bronchus and lung, Colon, Ovary, Bones, joints and articular cartilage of other and unspecified sites, Skin, Small intestine, Esophagus, Brain]","[Complex Mixed and Stromal Neoplasms, Acinar Cell Neoplasms, Adenomas and Adenocarcinomas, Squamous Cell Neoplasms, Gliomas, Fibromatous Neoplasms, Soft Tissue Tumors and Sarcomas, NOS, Myomatous Neoplasms, Blood Vessel Tumors, Osseous and Chondromatous Neoplasms, Ductal and Lobular Neoplasms, Cystic, Mucinous and Serous Neoplasms, Miscellaneous Bone Tumors, Nevi and Melanomas, Complex Epithelial Neoplasms, Epithelial Neoplasms, NOS]",NCI Cancer Model Development for the Human Cancer Model Initiative,True,open,True,"[{'file_count': 8086, 'case_count': 276, 'experimental_strategy': 'WXS'}, {'file_count': 4318, 'case_count': 277, 'experimental_strategy': 'WGS'}, {'file_count': 4768, 'case_count': 277, 'experimental_strategy': 'RNA-Seq'}, {'file_count': 1353, 'case_count': 267, 'experimental_strategy': 'Methylation Array'}, {'file_count': 314, 'case_count': 152, 'experimental_strategy': 'Tissue Slide'}]"
1,TCGA-BRCA,[Breast],"[Cystic, Mucinous and Serous Neoplasms, Complex Epithelial Neoplasms, Ductal and Lobular Neoplasms, Squamous Cell Neoplasms, Adenomas and Adenocarcinomas, Basal Cell Neoplasms, Epithelial Neoplasms, NOS, Adnexal and Skin Appendage Neoplasms, Fibroepithelial Neoplasms]",Breast Invasive Carcinoma,True,open,True,"[{'file_count': 11079, 'case_count': 1095, 'experimental_strategy': 'RNA-Seq'}, {'file_count': 17049, 'case_count': 1072, 'experimental_strategy': 'WXS'}, {'file_count': 3621, 'case_count': 1079, 'experimental_strategy': 'miRNA-Seq'}, {'file_count': 2783, 'case_count': 952, 'experimental_strategy': 'WGS'}, {'file_count': 75, 'case_count': 74, 'experimental_strategy': 'ATAC-Seq'}, {'file_count': 14329, 'case_count': 1098, 'experimental_strategy': 'Genotyping Array'}, {'file_count': 3714, 'case_count': 1097, 'experimental_strategy': 'Methylation Array'}, {'file_count': 919, 'case_count': 881, 'experimental_strategy': 'Reverse Phase Protein Array'}, {'file_count': 1133, 'case_count': 1062, 'experimental_strategy': 'Diagnostic Slide'}, {'file_count': 1978, 'case_count': 1093, 'experimental_strategy': 'Tissue Slide'}]"
2,TARGET-ALL-P3,"[Unknown, Hematopoietic and reticuloendothelial systems]","[Myeloid Leukemias, Leukemias, NOS, Not Applicable, Lymphoid Leukemias]",Acute Lymphoblastic Leukemia - Phase III,True,open,True,"[{'file_count': 2145, 'case_count': 89, 'experimental_strategy': 'WXS'}, {'file_count': 117, 'case_count': 38, 'experimental_strategy': 'miRNA-Seq'}, {'file_count': 945, 'case_count': 110, 'experimental_strategy': 'RNA-Seq'}, {'file_count': 103, 'case_count': 46, 'experimental_strategy': 'WGS'}, {'file_count': 423, 'case_count': 102, 'experimental_strategy': 'Methylation Array'}]"
3,EXCEPTIONAL_RESPONDERS-ER,"[Other and unspecified female genital organs, Connective, subcutaneous and other soft tissues, Bladder, Stomach, Other and ill-defined sites, Skin, Kidney, Bronchus and lung, Esophagus, Ovary, Anus and anal canal, Other and unspecified parts of biliary tract, Unknown, Rectum, Pancreas, Other and ill-defined digestive organs, Brain, Uterus, NOS, Colon, Breast]","[Nevi and Melanomas, Squamous Cell Neoplasms, Complex Mixed and Stromal Neoplasms, Gliomas, Ductal and Lobular Neoplasms, Adenomas and Adenocarcinomas, Neoplasms, NOS, Epithelial Neoplasms, NOS, Myomatous Neoplasms]",Exceptional Responders,False,open,True,"[{'file_count': 427, 'case_count': 82, 'experimental_strategy': 'WXS'}, {'file_count': 272, 'case_count': 69, 'experimental_strategy': 'Targeted Sequencing'}, {'file_count': 844, 'case_count': 70, 'experimental_strategy': 'RNA-Seq'}]"
4,CGCI-HTMCP-LC,[Bronchus and lung],"[Squamous Cell Neoplasms, Complex Epithelial Neoplasms, Paragangliomas and Glomus Tumors, Adenomas and Adenocarcinomas, Neoplasms, NOS, Epithelial Neoplasms, NOS]",HIV+ Tumor Molecular Characterization Project - Lung Cancer,False,open,True,"[{'file_count': 342, 'case_count': 38, 'experimental_strategy': 'RNA-Seq'}, {'file_count': 279, 'case_count': 39, 'experimental_strategy': 'WGS'}, {'file_count': 111, 'case_count': 37, 'experimental_strategy': 'miRNA-Seq'}, {'file_count': 84, 'case_count': 27, 'experimental_strategy': 'Tissue Slide'}]"
5,CPTAC-2,"[Other and unspecified female genital organs, Colon, Retroperitoneum and peritoneum, Rectum, Breast, Ovary]","[Cystic, Mucinous and Serous Neoplasms, Squamous Cell Neoplasms, Not Reported, Ductal and Lobular Neoplasms, Adenomas and Adenocarcinomas]","CPTAC-Breast, Colon, Ovary",True,open,True,"[{'file_count': 5254, 'case_count': 340, 'experimental_strategy': 'WXS'}, {'file_count': 930, 'case_count': 310, 'experimental_strategy': 'miRNA-Seq'}, {'file_count': 3060, 'case_count': 340, 'experimental_strategy': 'RNA-Seq'}]"
6,CMI-MBC,[Breast],[Ductal and Lobular Neoplasms],Count Me In (CMI): The Metastatic Breast Cancer (MBC) Project,True,open,True,"[{'file_count': 3627, 'case_count': 180, 'experimental_strategy': 'WXS'}, {'file_count': 1827, 'case_count': 140, 'experimental_strategy': 'RNA-Seq'}]"
7,TARGET-ALL-P2,[Hematopoietic and reticuloendothelial systems],[Lymphoid Leukemias],Acute Lymphoblastic Leukemia - Phase II,True,open,True,"[{'file_count': 11792, 'case_count': 784, 'experimental_strategy': 'WXS'}, {'file_count': 3724, 'case_count': 469, 'experimental_strategy': 'RNA-Seq'}, {'file_count': 153, 'case_count': 77, 'experimental_strategy': 'WGS'}, {'file_count': 693, 'case_count': 191, 'experimental_strategy': 'miRNA-Seq'}, {'file_count': 1212, 'case_count': 330, 'experimental_strategy': 'Genotyping Array'}]"
8,OHSU-CNL,[Hematopoietic and reticuloendothelial systems],[Chronic Myeloproliferative Disorders],Philadelphia-Negative Neutrophilic Leukemias (CNL/aCML/MDS/MPNu),True,open,True,"[{'file_count': 908, 'case_count': 158, 'experimental_strategy': 'WXS'}, {'file_count': 720, 'case_count': 80, 'experimental_strategy': 'RNA-Seq'}]"
9,TARGET-ALL-P1,[Hematopoietic and reticuloendothelial systems],[Lymphoid Leukemias],Acute Lymphoblastic Leukemia - Phase I,True,open,True,"[{'file_count': 84, 'case_count': 12, 'experimental_strategy': 'RNA-Seq'}, {'file_count': 12, 'case_count': 10, 'experimental_strategy': 'WGS'}]"

## Projetos Públicos com miRNA-Seq e RNA-Seq

In [15]:
# Campos de interesse no endpoint
fields = [
    'disease_type',
    'name',
    'primary_site',
]
fields = ','.join(fields)

# Filtros a serem empregados na requisição ao
filters = {
    'op': 'and',
    'content': [
        {
            'op': '=',
            'content': {
                'field': 'state',
                'value': 'open'
            }
        },
        {
            'op': 'in',
            'content': {
                'field': 'summary.experimental_strategies.experimental_strategy',
                'value': ['miRNA-Seq', 'RNA-Seq']
            }
        }
    ]
}

# Busca por todos os objetos da API
response = requests.post(
    url=PROJECTS_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields, 'filters': filters}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Transforma os valores booleanos em strings
for index in range(len(json_response)):
    obj = json_response[index]
    for key in obj:
        if isinstance(obj[key], bool): 
            obj[key] = str(obj[key])

# Converte o JSON para um DataFrame pandas
df_projects = pd.json_normalize(json_response)

# Printa o DataFrame completo
df_projects

,id,primary_site,disease_type,name
0,HCMI-CMDC,"[Connective, subcutaneous and other soft tissues, Other and unspecified parts of tongue, Other and unspecified parts of biliary tract, Other and unspecified parts of mouth, Rectum, Uterus, NOS, Pancreas, Corpus uteri, Other and ill-defined sites, Gallbladder, Breast, Kidney, Nasal cavity and middle ear, Liver and intrahepatic bile ducts, Rectosigmoid junction, Stomach, Bronchus and lung, Colon, Ovary, Bones, joints and articular cartilage of other and unspecified sites, Skin, Small intestine, Esophagus, Brain]","[Complex Mixed and Stromal Neoplasms, Acinar Cell Neoplasms, Adenomas and Adenocarcinomas, Squamous Cell Neoplasms, Gliomas, Fibromatous Neoplasms, Soft Tissue Tumors and Sarcomas, NOS, Myomatous Neoplasms, Blood Vessel Tumors, Osseous and Chondromatous Neoplasms, Ductal and Lobular Neoplasms, Cystic, Mucinous and Serous Neoplasms, Miscellaneous Bone Tumors, Nevi and Melanomas, Complex Epithelial Neoplasms, Epithelial Neoplasms, NOS]",NCI Cancer Model Development for the Human Cancer Model Initiative
1,TCGA-BRCA,[Breast],"[Cystic, Mucinous and Serous Neoplasms, Complex Epithelial Neoplasms, Ductal and Lobular Neoplasms, Squamous Cell Neoplasms, Adenomas and Adenocarcinomas, Basal Cell Neoplasms, Epithelial Neoplasms, NOS, Adnexal and Skin Appendage Neoplasms, Fibroepithelial Neoplasms]",Breast Invasive Carcinoma
2,TARGET-ALL-P3,"[Unknown, Hematopoietic and reticuloendothelial systems]","[Myeloid Leukemias, Leukemias, NOS, Not Applicable, Lymphoid Leukemias]",Acute Lymphoblastic Leukemia - Phase III
3,EXCEPTIONAL_RESPONDERS-ER,"[Other and unspecified female genital organs, Connective, subcutaneous and other soft tissues, Bladder, Stomach, Other and ill-defined sites, Skin, Kidney, Bronchus and lung, Esophagus, Ovary, Anus and anal canal, Other and unspecified parts of biliary tract, Unknown, Rectum, Pancreas, Other and ill-defined digestive organs, Brain, Uterus, NOS, Colon, Breast]","[Nevi and Melanomas, Squamous Cell Neoplasms, Complex Mixed and Stromal Neoplasms, Gliomas, Ductal and Lobular Neoplasms, Adenomas and Adenocarcinomas, Neoplasms, NOS, Epithelial Neoplasms, NOS, Myomatous Neoplasms]",Exceptional Responders
4,CGCI-HTMCP-LC,[Bronchus and lung],"[Squamous Cell Neoplasms, Complex Epithelial Neoplasms, Paragangliomas and Glomus Tumors, Adenomas and Adenocarcinomas, Neoplasms, NOS, Epithelial Neoplasms, NOS]",HIV+ Tumor Molecular Characterization Project - Lung Cancer
5,CPTAC-2,"[Other and unspecified female genital organs, Colon, Retroperitoneum and peritoneum, Rectum, Breast, Ovary]","[Cystic, Mucinous and Serous Neoplasms, Squamous Cell Neoplasms, Not Reported, Ductal and Lobular Neoplasms, Adenomas and Adenocarcinomas]","CPTAC-Breast, Colon, Ovary"
6,CMI-MBC,[Breast],[Ductal and Lobular Neoplasms],Count Me In (CMI): The Metastatic Breast Cancer (MBC) Project
7,TARGET-ALL-P2,[Hematopoietic and reticuloendothelial systems],[Lymphoid Leukemias],Acute Lymphoblastic Leukemia - Phase II
8,OHSU-CNL,[Hematopoietic and reticuloendothelial systems],[Chronic Myeloproliferative Disorders],Philadelphia-Negative Neutrophilic Leukemias (CNL/aCML/MDS/MPNu)
9,TARGET-ALL-P1,[Hematopoietic and reticuloendothelial systems],[Lymphoid Leukemias],Acute Lymphoblastic Leukemia - Phase I