# **Exploração da API do The Cancer Genome Atlas (TCGA)**
Desenvolvida pela Genomic Data Commons (GDC)

# Importação de Bibliotecas

In [1]:
import json
import pandas as pd
import requests

# Constantes

In [2]:
# URL HTML base da API TCGA / GDC
TCGA_API_ENDPOINT = 'https://api.gdc.cancer.gov'

# "Search annotations added to data after curation"
ANNOTATIONS_ENDPOINT = f'{TCGA_API_ENDPOINT}/annotations'

# "Find all files related to a specific case, or sample donor"
CASES_ENDPOINT = f'{TCGA_API_ENDPOINT}/cases'

# "Used to download GDC data"
DATA_ENDPOINT = f'{TCGA_API_ENDPOINT}/data'

# "Find all files with specific characteristics such as file_name, md5sum, data_format and others"
FILES_ENDPOINT = f'{TCGA_API_ENDPOINT}/files'

# "Generates manifests for use with GDC Data Transfer Tool"
MANIFEST_ENDPOINT = f'{TCGA_API_ENDPOINT}/manifest'

# "Search all data generated by a project"
PROJECTS_ENDPOINT = f'{TCGA_API_ENDPOINT}/projects'

# "Allows remote slicing of BAM format objects"
SLICING_ENDPOINT = f'{TCGA_API_ENDPOINT}/slicing'

# "Get the API status and version information"
STATUS_ENDPOINT = f'{TCGA_API_ENDPOINT}/status'

# "Returns the available resources at the top level above programs i.e., registered programs"
SUBMISSION_ENDPOINT = f'{TCGA_API_ENDPOINT}/submission'

# Exploração dos Endpoints

## `status`

In [3]:
# Verifica o status e a versão da API
response = requests.get(STATUS_ENDPOINT)

# Printa o conteúdo da resposta
print(response.content.decode('utf-8'))

{"commit":"3ed4235efe2f2d9c9969e1ce790e6b34a5c60c9d","data_release":"Data Release 41.0 - August 28, 2024","status":"OK","tag":"7.4.0","version":1}

## `projects`

In [4]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{PROJECTS_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON e printa os campos do endpoint
json_response = json.loads(response.content.decode('utf-8'))
json_response_str = json.dumps(json_response['fields'], indent=2)
print(json_response_str)

[
  "dbgap_accession_number",
  "disease_type",
  "intended_release_date",
  "name",
  "primary_site",
  "program.dbgap_accession_number",
  "program.name",
  "program.program_id",
  "project_autocomplete",
  "project_id",
  "releasable",
  "released",
  "state",
  "summary.case_count",
  "summary.data_categories.case_count",
  "summary.data_categories.data_category",
  "summary.data_categories.file_count",
  "summary.experimental_strategies.case_count",
  "summary.experimental_strategies.experimental_strategy",
  "summary.experimental_strategies.file_count",
  "summary.file_count",
  "summary.file_size"
]

In [5]:
# Campos disponíveis no endpoint
fields = [
    'dbgap_accession_number',
    'disease_type',
    'intended_release_date',
    'name',
    'primary_site',
    'program.dbgap_accession_number',
    'program.name',
    'program.program_id',
    'project_autocomplete',
    'project_id',
    'releasable',
    'released',
    'state',
    'summary.case_count',
    'summary.data_categories.case_count',
    'summary.data_categories.data_category',
    'summary.data_categories.file_count',
    'summary.experimental_strategies.case_count',
    'summary.experimental_strategies.experimental_strategy',
    'summary.experimental_strategies.file_count',
    'summary.file_count',
    'summary.file_size'
]
fields = ','.join(fields)

# Busca por todos os projetos da API
response = requests.post(
    url=PROJECTS_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Printa um dos objetos do conteúdo da resposta
json_response_str = json.dumps(json_response[1], indent=2)
print(json_response_str)

{
  "id": "MATCH-Z1I",
  "summary": {
    "file_count": 660,
    "data_categories": [
      {
        "file_count": 327,
        "case_count": 24,
        "data_category": "Simple Nucleotide Variation"
      },
      {
        "file_count": 125,
        "case_count": 26,
        "data_category": "Sequencing Reads"
      },
      {
        "file_count": 26,
        "case_count": 26,
        "data_category": "Biospecimen"
      },
      {
        "file_count": 26,
        "case_count": 26,
        "data_category": "Clinical"
      },
      {
        "file_count": 52,
        "case_count": 26,
        "data_category": "Transcriptome Profiling"
      },
      {
        "file_count": 104,
        "case_count": 26,
        "data_category": "Structural Variation"
      }
    ],
    "experimental_strategies": [
      {
        "file_count": 374,
        "case_count": 24,
        "experimental_strategy": "WXS"
      },
      {
        "file_count": 234,
        "case_count": 26,
        "experimental_strategy": "RNA-Seq"
      }
    ],
    "case_count": 26,
    "file_size": 2396549656405
  },
  "primary_site": [
    "Bronchus and lung",
    "Gallbladder",
    "Pancreas",
    "Unknown",
    "Other and ill-defined sites in lip, oral cavity and pharynx",
    "Other and unspecified female genital organs",
    "Parotid gland",
    "Rectosigmoid junction",
    "Breast",
    "Anus and anal canal",
    "Ovary",
    "Rectum"
  ],
  "dbgap_accession_number": "phs002058",
  "project_id": "MATCH-Z1I",
  "disease_type": [
    "Squamous Cell Neoplasms",
    "Epithelial Neoplasms, NOS",
    "Nevi and Melanomas",
    "Ductal and Lobular Neoplasms",
    "Adenomas and Adenocarcinomas",
    "Neoplasms, NOS"
  ],
  "name": "Genomic Characterization CS-MATCH-0007 Arm Z1I",
  "releasable": false,
  "state": "open",
  "program": {
    "dbgap_accession_number": null,
    "program_id": "893b0820-b50b-5c75-85f5-3b028e251811",
    "name": "MATCH"
  },
  "released": true
}

## `cases`

In [6]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{CASES_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON e printa os campos do endpoint
json_response = json.loads(response.content.decode('utf-8'))
json_response_str = json.dumps(json_response['fields'], indent=2)
print(json_response_str)

[
  "aliquot_ids",
  "analyte_ids",
  "annotations.annotation_id",
  "annotations.case_id",
  "annotations.case_submitter_id",
  "annotations.category",
  "annotations.classification",
  "annotations.created_datetime",
  "annotations.creator",
  "annotations.entity_id",
  "annotations.entity_submitter_id",
  "annotations.entity_type",
  "annotations.legacy_created_datetime",
  "annotations.legacy_updated_datetime",
  "annotations.notes",
  "annotations.state",
  "annotations.status",
  "annotations.submitter_id",
  "annotations.updated_datetime",
  "case_autocomplete",
  "case_id",
  "consent_type",
  "created_datetime",
  "days_to_consent",
  "days_to_lost_to_followup",
  "demographic.age_at_index",
  "demographic.age_is_obfuscated",
  "demographic.cause_of_death",
  "demographic.cause_of_death_source",
  "demographic.country_of_birth",
  "demographic.country_of_residence_at_enrollment",
  "demographic.created_datetime",
  "demographic.days_to_birth",
  "demographic.days_to_death",
  "demographic.demographic_id",
  "demographic.education_level",
  "demographic.ethnicity",
  "demographic.gender",
  "demographic.marital_status",
  "demographic.occupation_duration_years",
  "demographic.premature_at_birth",
  "demographic.race",
  "demographic.state",
  "demographic.submitter_id",
  "demographic.updated_datetime",
  "demographic.vital_status",
  "demographic.weeks_gestation_at_birth",
  "demographic.year_of_birth",
  "demographic.year_of_death",
  "diagnoses.adrenal_hormone",
  "diagnoses.age_at_diagnosis",
  "diagnoses.ajcc_clinical_m",
  "diagnoses.ajcc_clinical_n",
  "diagnoses.ajcc_clinical_stage",
  "diagnoses.ajcc_clinical_t",
  "diagnoses.ajcc_pathologic_m",
  "diagnoses.ajcc_pathologic_n",
  "diagnoses.ajcc_pathologic_stage",
  "diagnoses.ajcc_pathologic_t",
  "diagnoses.ajcc_staging_system_edition",
  "diagnoses.ann_arbor_b_symptoms",
  "diagnoses.ann_arbor_b_symptoms_described",
  "diagnoses.ann_arbor_clinical_stage",
  "diagnoses.ann_arbor_extranodal_involvement",
  "diagnoses.ann_arbor_pathologic_stage",
  "diagnoses.annotations.annotation_id",
  "diagnoses.annotations.case_id",
  "diagnoses.annotations.case_submitter_id",
  "diagnoses.annotations.category",
  "diagnoses.annotations.classification",
  "diagnoses.annotations.created_datetime",
  "diagnoses.annotations.creator",
  "diagnoses.annotations.entity_id",
  "diagnoses.annotations.entity_submitter_id",
  "diagnoses.annotations.entity_type",
  "diagnoses.annotations.legacy_created_datetime",
  "diagnoses.annotations.legacy_updated_datetime",
  "diagnoses.annotations.notes",
  "diagnoses.annotations.state",
  "diagnoses.annotations.status",
  "diagnoses.annotations.submitter_id",
  "diagnoses.annotations.updated_datetime",
  "diagnoses.best_overall_response",
  "diagnoses.burkitt_lymphoma_clinical_variant",
  "diagnoses.calgb_risk_group",
  "diagnoses.cancer_detection_method",
  "diagnoses.child_pugh_classification",
  "diagnoses.clark_level",
  "diagnoses.classification_of_tumor",
  "diagnoses.cog_liver_stage",
  "diagnoses.cog_neuroblastoma_risk_group",
  "diagnoses.cog_renal_stage",
  "diagnoses.cog_rhabdomyosarcoma_risk_group",
  "diagnoses.contiguous_organ_invaded",
  "diagnoses.created_datetime",
  "diagnoses.days_to_best_overall_response",
  "diagnoses.days_to_diagnosis",
  "diagnoses.days_to_last_follow_up",
  "diagnoses.days_to_last_known_disease_status",
  "diagnoses.days_to_recurrence",
  "diagnoses.diagnosis_id",
  "diagnoses.diagnosis_is_primary_disease",
  "diagnoses.double_expressor_lymphoma",
  "diagnoses.double_hit_lymphoma",
  "diagnoses.eln_risk_classification",
  "diagnoses.enneking_msts_grade",
  "diagnoses.enneking_msts_metastasis",
  "diagnoses.enneking_msts_stage",
  "diagnoses.enneking_msts_tumor_site",
  "diagnoses.ensat_clinical_m",
  "diagnoses.ensat_pathologic_n",
  "diagnoses.ensat_pathologic_stage",
  "diagnoses.ensat_pathologic_t",
  "diagnoses.esophageal_columnar_dysplasia_degree",
  "diagnoses.esophageal_columnar_metaplasia_present",
  "diagnoses.fab_morphology_code",
  "diagnoses.figo_stage",
  "diagnoses.figo_staging_edition_year",
  "diagnoses.first_symptom_longest_duration",
  "diagnoses.first_symptom_prior_to_diagnosis",
  "diagnoses.gastric_esophageal_junction_involvement",
  "diagnoses.gleason_grade_group",
  "diagnoses.gleason_grade_tertiary",
  "diagnoses.gleason_patterns_percent",
  "diagnoses.gleason_score",
  "diagnoses.goblet_cells_columnar_mucosa_present",
  "diagnoses.icd_10_code",
  "diagnoses.igcccg_stage",
  "diagnoses.inpc_grade",
  "diagnoses.inpc_histologic_group",
  "diagnoses.inrg_stage",
  "diagnoses.inss_stage",
  "diagnoses.international_prognostic_index",
  "diagnoses.irs_group",
  "diagnoses.irs_stage",
  "diagnoses.ishak_fibrosis_score",
  "diagnoses.iss_stage",
  "diagnoses.last_known_disease_status",
  "diagnoses.laterality",
  "diagnoses.margin_distance",
  "diagnoses.margins_involved_site",
  "diagnoses.masaoka_stage",
  "diagnoses.max_tumor_bulk_site",
  "diagnoses.medulloblastoma_molecular_classification",
  "diagnoses.melanoma_known_primary",
  "diagnoses.metastasis_at_diagnosis",
  "diagnoses.metastasis_at_diagnosis_site",
  "diagnoses.method_of_diagnosis",
  "diagnoses.micropapillary_features",
  "diagnoses.mitosis_karyorrhexis_index",
  "diagnoses.mitotic_count",
  "diagnoses.morphology",
  "diagnoses.ovarian_specimen_status",
  "diagnoses.ovarian_surface_involvement",
  "diagnoses.papillary_renal_cell_type",
  "diagnoses.pathology_details.additional_pathology_findings",
  "diagnoses.pathology_details.anaplasia_present",
  "diagnoses.pathology_details.anaplasia_present_type",
  "diagnoses.pathology_details.bone_marrow_malignant_cells",
  "diagnoses.pathology_details.breslow_thickness",
  "diagnoses.pathology_details.circumferential_resection_margin",
  "diagnoses.pathology_details.columnar_mucosa_present",
  "diagnoses.pathology_details.consistent_pathology_review",
  "diagnoses.pathology_details.created_datetime",
  "diagnoses.pathology_details.days_to_pathology_detail",
  "diagnoses.pathology_details.dysplasia_degree",
  "diagnoses.pathology_details.dysplasia_type",
  "diagnoses.pathology_details.epithelioid_cell_percent",
  "diagnoses.pathology_details.extracapsular_extension",
  "diagnoses.pathology_details.extracapsular_extension_present",
  "diagnoses.pathology_details.extranodal_extension",
  "diagnoses.pathology_details.extrascleral_extension",
  "diagnoses.pathology_details.extrathyroid_extension",
  "diagnoses.pathology_details.greatest_tumor_dimension",
  "diagnoses.pathology_details.gross_tumor_weight",
  "diagnoses.pathology_details.histologic_progression_type",
  "diagnoses.pathology_details.largest_extrapelvic_peritoneal_focus",
  "diagnoses.pathology_details.lymph_node_dissection_method",
  "diagnoses.pathology_details.lymph_node_dissection_site",
  "diagnoses.pathology_details.lymph_node_involved_site",
  "diagnoses.pathology_details.lymph_node_involvement",
  "diagnoses.pathology_details.lymph_nodes_positive",
  "diagnoses.pathology_details.lymph_nodes_removed",
  "diagnoses.pathology_details.lymph_nodes_tested",
  "diagnoses.pathology_details.lymphatic_invasion_present",
  "diagnoses.pathology_details.margin_status",
  "diagnoses.pathology_details.measurement_type",
  "diagnoses.pathology_details.measurement_unit",
  "diagnoses.pathology_details.metaplasia_present",
  "diagnoses.pathology_details.micrometastasis_present",
  "diagnoses.pathology_details.morphologic_architectural_pattern",
  "diagnoses.pathology_details.necrosis_percent",
  "diagnoses.pathology_details.necrosis_present",
  "diagnoses.pathology_details.non_nodal_regional_disease",
  "diagnoses.pathology_details.non_nodal_tumor_deposits",
  "diagnoses.pathology_details.number_proliferating_cells",
  "diagnoses.pathology_details.pathology_detail_id",
  "diagnoses.pathology_details.percent_tumor_invasion",
  "diagnoses.pathology_details.percent_tumor_nuclei",
  "diagnoses.pathology_details.perineural_invasion_present",
  "diagnoses.pathology_details.peripancreatic_lymph_nodes_positive",
  "diagnoses.pathology_details.peripancreatic_lymph_nodes_tested",
  "diagnoses.pathology_details.prcc_type",
  "diagnoses.pathology_details.prostatic_chips_positive_count",
  "diagnoses.pathology_details.prostatic_chips_total_count",
  "diagnoses.pathology_details.prostatic_involvement_percent",
  "diagnoses.pathology_details.residual_tumor",
  "diagnoses.pathology_details.residual_tumor_measurement",
  "diagnoses.pathology_details.rhabdoid_percent",
  "diagnoses.pathology_details.rhabdoid_present",
  "diagnoses.pathology_details.sarcomatoid_percent",
  "diagnoses.pathology_details.sarcomatoid_present",
  "diagnoses.pathology_details.size_extraocular_nodule",
  "diagnoses.pathology_details.spindle_cell_percent",
  "diagnoses.pathology_details.state",
  "diagnoses.pathology_details.submitter_id",
  "diagnoses.pathology_details.transglottic_extension",
  "diagnoses.pathology_details.tumor_burden",
  "diagnoses.pathology_details.tumor_depth_descriptor",
  "diagnoses.pathology_details.tumor_depth_measurement",
  "diagnoses.pathology_details.tumor_infiltrating_lymphocytes",
  "diagnoses.pathology_details.tumor_infiltrating_macrophages",
  "diagnoses.pathology_details.tumor_largest_dimension_diameter",
  "diagnoses.pathology_details.tumor_length_measurement",
  "diagnoses.pathology_details.tumor_level_prostate",
  "diagnoses.pathology_details.tumor_shape",
  "diagnoses.pathology_details.tumor_thickness",
  "diagnoses.pathology_details.tumor_width_measurement",
  "diagnoses.pathology_details.updated_datetime",
  "diagnoses.pathology_details.vascular_invasion_present",
  "diagnoses.pathology_details.vascular_invasion_type",
  "diagnoses.pathology_details.zone_of_origin_prostate",
  "diagnoses.pediatric_kidney_staging",
  "diagnoses.peritoneal_fluid_cytological_status",
  "diagnoses.pregnant_at_diagnosis",
  "diagnoses.primary_diagnosis",
  "diagnoses.primary_disease",
  "diagnoses.primary_gleason_grade",
  "diagnoses.prior_malignancy",
  "diagnoses.prior_treatment",
  "diagnoses.progression_or_recurrence",
  "diagnoses.residual_disease",
  "diagnoses.satellite_nodule_present",
  "diagnoses.secondary_gleason_grade",
  "diagnoses.site_of_resection_or_biopsy",
  "diagnoses.sites_of_involvement",
  "diagnoses.sites_of_involvement_count",
  "diagnoses.state",
  "diagnoses.submitter_id",
  "diagnoses.supratentorial_localization",
  "diagnoses.synchronous_malignancy",
  "diagnoses.tissue_or_organ_of_origin",
  "diagnoses.treatments.chemo_concurrent_to_radiation",
  "diagnoses.treatments.clinical_trial_indicator",
  "diagnoses.treatments.course_number",
  "diagnoses.treatments.created_datetime",
  "diagnoses.treatments.days_to_treatment_end",
  "diagnoses.treatments.days_to_treatment_start",
  "diagnoses.treatments.drug_category",
  "diagnoses.treatments.embolic_agent",
  "diagnoses.treatments.initial_disease_status",
  "diagnoses.treatments.lesions_treated_number",
  "diagnoses.treatments.number_of_cycles",
  "diagnoses.treatments.number_of_fractions",
  "diagnoses.treatments.prescribed_dose",
  "diagnoses.treatments.prescribed_dose_units",
  "diagnoses.treatments.protocol_identifier",
  "diagnoses.treatments.radiosensitizing_agent",
  "diagnoses.treatments.reason_treatment_ended",
  "diagnoses.treatments.reason_treatment_not_given",
  "diagnoses.treatments.regimen_or_line_of_therapy",
  "diagnoses.treatments.residual_disease",
  "diagnoses.treatments.route_of_administration",
  "diagnoses.treatments.state",
  "diagnoses.treatments.submitter_id",
  "diagnoses.treatments.therapeutic_agents",
  "diagnoses.treatments.therapeutic_level_achieved",
  "diagnoses.treatments.therapeutic_levels_achieved",
  "diagnoses.treatments.therapeutic_target_level",
  "diagnoses.treatments.timepoint_category",
  "diagnoses.treatments.treatment_anatomic_site",
  "diagnoses.treatments.treatment_anatomic_sites",
  "diagnoses.treatments.treatment_arm",
  "diagnoses.treatments.treatment_dose",
  "diagnoses.treatments.treatment_dose_max",
  "diagnoses.treatments.treatment_dose_units",
  "diagnoses.treatments.treatment_duration",
  "diagnoses.treatments.treatment_effect",
  "diagnoses.treatments.treatment_effect_indicator",
  "diagnoses.treatments.treatment_frequency",
  "diagnoses.treatments.treatment_id",
  "diagnoses.treatments.treatment_intent_type",
  "diagnoses.treatments.treatment_or_therapy",
  "diagnoses.treatments.treatment_outcome",
  "diagnoses.treatments.treatment_outcome_duration",
  "diagnoses.treatments.treatment_type",
  "diagnoses.treatments.updated_datetime",
  "diagnoses.tumor_burden",
  "diagnoses.tumor_confined_to_organ_of_origin",
  "diagnoses.tumor_depth",
  "diagnoses.tumor_focality",
  "diagnoses.tumor_grade",
  "diagnoses.tumor_grade_category",
  "diagnoses.tumor_of_origin",
  "diagnoses.tumor_regression_grade",
  "diagnoses.uicc_clinical_m",
  "diagnoses.uicc_clinical_n",
  "diagnoses.uicc_clinical_stage",
  "diagnoses.uicc_clinical_t",
  "diagnoses.uicc_pathologic_m",
  "diagnoses.uicc_pathologic_n",
  "diagnoses.uicc_pathologic_stage",
  "diagnoses.uicc_pathologic_t",
  "diagnoses.uicc_staging_system_edition",
  "diagnoses.ulceration_indicator",
  "diagnoses.updated_datetime",
  "diagnoses.weiss_assessment_findings",
  "diagnoses.weiss_assessment_score",
  "diagnoses.who_cns_grade",
  "diagnoses.who_nte_grade",
  "diagnoses.wilms_tumor_histologic_subtype",
  "diagnoses.year_of_diagnosis",
  "diagnoses.anaplasia_present",
  "diagnoses.anaplasia_present_type",
  "diagnoses.breslow_thickness",
  "diagnoses.circumferential_resection_margin",
  "diagnoses.greatest_tumor_dimension",
  "diagnoses.gross_tumor_weight",
  "diagnoses.largest_extrapelvic_peritoneal_focus",
  "diagnoses.lymph_node_involved_site",
  "diagnoses.lymph_nodes_positive",
  "diagnoses.lymph_nodes_tested",
  "diagnoses.lymphatic_invasion_present",
  "diagnoses.non_nodal_regional_disease",
  "diagnoses.non_nodal_tumor_deposits",
  "diagnoses.percent_tumor_invasion",
  "diagnoses.perineural_invasion_present",
  "diagnoses.peripancreatic_lymph_nodes_positive",
  "diagnoses.peripancreatic_lymph_nodes_tested",
  "diagnoses.transglottic_extension",
  "diagnoses.tumor_largest_dimension_diameter",
  "diagnoses.tumor_stage",
  "diagnoses.vascular_invasion_present",
  "diagnoses.vascular_invasion_type",
  "diagnosis_ids",
  "disease_type",
  "exposures.age_at_last_exposure",
  "exposures.age_at_onset",
  "exposures.alcohol_days_per_week",
  "exposures.alcohol_drinks_per_day",
  "exposures.alcohol_frequency",
  "exposures.alcohol_history",
  "exposures.alcohol_intensity",
  "exposures.alcohol_type",
  "exposures.asbestos_exposure",
  "exposures.asbestos_exposure_type",
  "exposures.chemical_exposure_type",
  "exposures.cigarettes_per_day",
  "exposures.coal_dust_exposure",
  "exposures.created_datetime",
  "exposures.environmental_tobacco_smoke_exposure",
  "exposures.exposure_duration",
  "exposures.exposure_duration_hrs_per_day",
  "exposures.exposure_duration_years",
  "exposures.exposure_id",
  "exposures.exposure_source",
  "exposures.exposure_type",
  "exposures.occupation_duration_years",
  "exposures.occupation_type",
  "exposures.pack_years_smoked",
  "exposures.parent_with_radiation_exposure",
  "exposures.radon_exposure",
  "exposures.respirable_crystalline_silica_exposure",
  "exposures.secondhand_smoke_as_child",
  "exposures.smoking_frequency",
  "exposures.state",
  "exposures.submitter_id",
  "exposures.time_between_waking_and_first_smoke",
  "exposures.tobacco_smoking_onset_year",
  "exposures.tobacco_smoking_quit_year",
  "exposures.tobacco_smoking_status",
  "exposures.type_of_smoke_exposure",
  "exposures.type_of_tobacco_used",
  "exposures.updated_datetime",
  "exposures.use_per_day",
  "exposures.years_smoked",
  "exposures.bmi",
  "exposures.height",
  "exposures.marijuana_use_per_week",
  "exposures.smokeless_tobacco_quit_age",
  "exposures.tobacco_use_per_day",
  "exposures.weight",
  "family_histories.created_datetime",
  "family_histories.family_history_id",
  "family_histories.relationship_age_at_diagnosis",
  "family_histories.relationship_gender",
  "family_histories.relationship_primary_diagnosis",
  "family_histories.relationship_type",
  "family_histories.relative_deceased",
  "family_histories.relative_smoker",
  "family_histories.relative_with_cancer_history",
  "family_histories.relatives_with_cancer_history_count",
  "family_histories.state",
  "family_histories.submitter_id",
  "family_histories.updated_datetime",
  "files.access",
  "files.acl",
  "files.analysis.analysis_id",
  "files.analysis.analysis_type",
  "files.analysis.created_datetime",
  "files.analysis.input_files.access",
  "files.analysis.input_files.average_base_quality",
  "files.analysis.input_files.average_insert_size",
  "files.analysis.input_files.average_read_length",
  "files.analysis.input_files.cancer_dna_fraction",
  "files.analysis.input_files.channel",
  "files.analysis.input_files.chip_id",
  "files.analysis.input_files.chip_position",
  "files.analysis.input_files.contamination",
  "files.analysis.input_files.contamination_error",
  "files.analysis.input_files.created_datetime",
  "files.analysis.input_files.data_category",
  "files.analysis.input_files.data_format",
  "files.analysis.input_files.data_type",
  "files.analysis.input_files.error_type",
  "files.analysis.input_files.experimental_strategy",
  "files.analysis.input_files.file_id",
  "files.analysis.input_files.file_name",
  "files.analysis.input_files.file_size",
  "files.analysis.input_files.genome_doubling",
  "files.analysis.input_files.imaging_date",
  "files.analysis.input_files.magnification",
  "files.analysis.input_files.md5sum",
  "files.analysis.input_files.mean_coverage",
  "files.analysis.input_files.msi_score",
  "files.analysis.input_files.msi_status",
  "files.analysis.input_files.pairs_on_diff_chr",
  "files.analysis.input_files.plate_name",
  "files.analysis.input_files.plate_well",
  "files.analysis.input_files.platform",
  "files.analysis.input_files.proc_internal",
  "files.analysis.input_files.proportion_base_mismatch",
  "files.analysis.input_files.proportion_coverage_10x",
  "files.analysis.input_files.proportion_coverage_30x",
  "files.analysis.input_files.proportion_reads_duplicated",
  "files.analysis.input_files.proportion_reads_mapped",
  "files.analysis.input_files.proportion_targets_no_coverage",
  "files.analysis.input_files.read_pair_number",
  "files.analysis.input_files.revision",
  "files.analysis.input_files.stain_type",
  "files.analysis.input_files.state",
  "files.analysis.input_files.state_comment",
  "files.analysis.input_files.subclonal_genome_fraction",
  "files.analysis.input_files.submitter_id",
  "files.analysis.input_files.total_reads",
  "files.analysis.input_files.tumor_ploidy",
  "files.analysis.input_files.tumor_purity",
  "files.analysis.input_files.updated_datetime",
  "files.analysis.input_files.wgs_coverage",
  "files.analysis.input_files.proportion_coverage_10X",
  "files.analysis.input_files.proportion_coverage_30X",
  "files.analysis.metadata.read_groups.adapter_name",
  "files.analysis.metadata.read_groups.adapter_sequence",
  "files.analysis.metadata.read_groups.base_caller_name",
  "files.analysis.metadata.read_groups.base_caller_version",
  "files.analysis.metadata.read_groups.chipseq_antibody",
  "files.analysis.metadata.read_groups.chipseq_target",
  "files.analysis.metadata.read_groups.created_datetime",
  "files.analysis.metadata.read_groups.days_to_sequencing",
  "files.analysis.metadata.read_groups.experiment_name",
  "files.analysis.metadata.read_groups.flow_cell_barcode",
  "files.analysis.metadata.read_groups.fragment_maximum_length",
  "files.analysis.metadata.read_groups.fragment_mean_length",
  "files.analysis.metadata.read_groups.fragment_minimum_length",
  "files.analysis.metadata.read_groups.fragment_standard_deviation_length",
  "files.analysis.metadata.read_groups.fragmentation_enzyme",

In [7]:
# Campos de interesse para a requisição ao endpoint
fields = [
    'case_id',
    'disease_type',
    'files.access',
    'files.data_category',
    'files.data_format',
    'files.data_type',
    'files.file_id',
    'files.experimental_strategy',
    'primary_site',
    'project.project_id',
    'state'
]
fields = ','.join(fields)

# Parâmetros para a requisição ao endpoint
params = {
    'fields': fields,
    'format': 'json'
}

# Busca por um dos objetos da API
response = requests.post(
    url=CASES_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields, 'size': '1'}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Printa um dos objetos do conteúdo da resposta
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

[
  {
    "id": "58771370-5082-485e-ac68-13edfbd9ef0c",
    "primary_site": "Hematopoietic and reticuloendothelial systems",
    "disease_type": "Myeloid Leukemias",
    "case_id": "58771370-5082-485e-ac68-13edfbd9ef0c",
    "project": {
      "project_id": "TARGET-AML"
    },
    "files": [
      {
        "data_format": "XLSX",
        "access": "open",
        "file_id": "52fd584b-9ca3-4f7e-bdd5-fd9dce3d630b",
        "data_type": "Clinical Supplement",
        "data_category": "Clinical"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "7e37b56e-4a47-4e14-aa0c-2317e31f3e53",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "2b213562-4c34-4976-9563-ef2e581eb993",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BEDPE",
        "access": "controlled",
        "file_id": "4188fa7a-7b11-47ae-ad63-701f5a2ffecb",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BEDPE",
        "access": "controlled",
        "file_id": "dd250c15-0be7-4243-b147-d4c872587844",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "619cea2a-d035-4979-ad83-b7863eefc337",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "37d76573-b322-4fdf-ab88-924ff88b882d",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "TSV",
        "access": "open",
        "file_id": "48bd466c-b8e4-4473-a5d3-45c7c9eccdf8",
        "data_type": "Gene Expression Quantification",
        "data_category": "Transcriptome Profiling",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BEDPE",
        "access": "controlled",
        "file_id": "934d6fdc-2465-4da6-9e78-f07a5881e3f8",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "e0ad7395-7f8a-4469-9080-72d721bf06b7",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "1ddf3bf1-29d2-42be-b686-bc04a84752fe",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "TSV",
        "access": "open",
        "file_id": "c87a81e0-5b0c-4c22-a542-1842f884b938",
        "data_type": "Gene Expression Quantification",
        "data_category": "Transcriptome Profiling",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "XLSX",
        "access": "open",
        "file_id": "68170d63-c297-4d93-a21b-7bb43b451a96",
        "data_type": "Clinical Supplement",
        "data_category": "Clinical"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "1b878c74-754a-416d-9f13-d299e21488e9",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "e8631201-d233-4002-8e45-69d19dae0e81",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "miRNA-Seq"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "02b2f584-aed0-4fac-80a6-1ef838aa4467",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "551cb6b7-c12e-4182-8c60-30d9f47f9ca4",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "a5ee3b40-519d-43e1-9a94-20e6216b1bd3",
        "data_type": "Splice Junction Quantification",
        "data_category": "Transcriptome Profiling",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "TSV",
        "access": "controlled",
        "file_id": "f0898299-c909-4392-8648-bc5eda1d9599",
        "data_type": "Splice Junction Quantification",
        "data_category": "Transcriptome Profiling",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BEDPE",
        "access": "controlled",
        "file_id": "18b3e160-79c2-492c-a1ab-10678378d12e",
        "data_type": "Transcript Fusion",
        "data_category": "Structural Variation",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "BAM",
        "access": "controlled",
        "file_id": "467a15b1-f616-47c5-b05c-808907723751",
        "data_type": "Aligned Reads",
        "data_category": "Sequencing Reads",
        "experimental_strategy": "RNA-Seq"
      },
      {
        "data_format": "TSV",
        "access": "open",
        "file_id": "38cae586-7e4c-4e46-ae39-ddaf022db2ae",
        "data_type": "Isoform Expression Quantification",
        "data_category": "Transcriptome Profiling",
        "experimental_strategy": "miRNA-Seq"
      },
      {
        "data_format": "TSV",
        "access": "open",
        "file_id": "f89d1708-d789-4ca8-b9b8-cf9021c01b27",
        "data_type": "miRNA Expression Quantification",
        "data_category": "Transcriptome Profiling",
        "experimental_strategy": "miRNA-Seq"
      }
    ],
    "state": "released"
  }
]

## `files`

In [8]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{FILES_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON e printa os campos do endpoint
json_response = json.loads(response.content.decode('utf-8'))
json_response_str = json.dumps(json_response['fields'], indent=2)
print(json_response_str)

[
  "access",
  "acl",
  "analysis.analysis_id",
  "analysis.analysis_type",
  "analysis.created_datetime",
  "analysis.input_files.access",
  "analysis.input_files.average_base_quality",
  "analysis.input_files.average_insert_size",
  "analysis.input_files.average_read_length",
  "analysis.input_files.cancer_dna_fraction",
  "analysis.input_files.channel",
  "analysis.input_files.chip_id",
  "analysis.input_files.chip_position",
  "analysis.input_files.contamination",
  "analysis.input_files.contamination_error",
  "analysis.input_files.created_datetime",
  "analysis.input_files.data_category",
  "analysis.input_files.data_format",
  "analysis.input_files.data_type",
  "analysis.input_files.error_type",
  "analysis.input_files.experimental_strategy",
  "analysis.input_files.file_id",
  "analysis.input_files.file_name",
  "analysis.input_files.file_size",
  "analysis.input_files.genome_doubling",
  "analysis.input_files.imaging_date",
  "analysis.input_files.magnification",
  "analysis.input_files.md5sum",
  "analysis.input_files.mean_coverage",
  "analysis.input_files.msi_score",
  "analysis.input_files.msi_status",
  "analysis.input_files.pairs_on_diff_chr",
  "analysis.input_files.plate_name",
  "analysis.input_files.plate_well",
  "analysis.input_files.platform",
  "analysis.input_files.proc_internal",
  "analysis.input_files.proportion_base_mismatch",
  "analysis.input_files.proportion_coverage_10x",
  "analysis.input_files.proportion_coverage_30x",
  "analysis.input_files.proportion_reads_duplicated",
  "analysis.input_files.proportion_reads_mapped",
  "analysis.input_files.proportion_targets_no_coverage",
  "analysis.input_files.read_pair_number",
  "analysis.input_files.revision",
  "analysis.input_files.stain_type",
  "analysis.input_files.state",
  "analysis.input_files.state_comment",
  "analysis.input_files.subclonal_genome_fraction",
  "analysis.input_files.submitter_id",
  "analysis.input_files.total_reads",
  "analysis.input_files.tumor_ploidy",
  "analysis.input_files.tumor_purity",
  "analysis.input_files.updated_datetime",
  "analysis.input_files.wgs_coverage",
  "analysis.input_files.proportion_coverage_10X",
  "analysis.input_files.proportion_coverage_30X",
  "analysis.metadata.read_groups.adapter_name",
  "analysis.metadata.read_groups.adapter_sequence",
  "analysis.metadata.read_groups.base_caller_name",
  "analysis.metadata.read_groups.base_caller_version",
  "analysis.metadata.read_groups.chipseq_antibody",
  "analysis.metadata.read_groups.chipseq_target",
  "analysis.metadata.read_groups.created_datetime",
  "analysis.metadata.read_groups.days_to_sequencing",
  "analysis.metadata.read_groups.experiment_name",
  "analysis.metadata.read_groups.flow_cell_barcode",
  "analysis.metadata.read_groups.fragment_maximum_length",
  "analysis.metadata.read_groups.fragment_mean_length",
  "analysis.metadata.read_groups.fragment_minimum_length",
  "analysis.metadata.read_groups.fragment_standard_deviation_length",
  "analysis.metadata.read_groups.fragmentation_enzyme",
  "analysis.metadata.read_groups.includes_spike_ins",
  "analysis.metadata.read_groups.instrument_model",
  "analysis.metadata.read_groups.is_paired_end",
  "analysis.metadata.read_groups.lane_number",
  "analysis.metadata.read_groups.library_name",
  "analysis.metadata.read_groups.library_preparation_kit_catalog_number",
  "analysis.metadata.read_groups.library_preparation_kit_name",
  "analysis.metadata.read_groups.library_preparation_kit_vendor",
  "analysis.metadata.read_groups.library_preparation_kit_version",
  "analysis.metadata.read_groups.library_selection",
  "analysis.metadata.read_groups.library_strand",
  "analysis.metadata.read_groups.library_strategy",
  "analysis.metadata.read_groups.multiplex_barcode",
  "analysis.metadata.read_groups.number_expect_cells",
  "analysis.metadata.read_groups.platform",
  "analysis.metadata.read_groups.read_group_id",
  "analysis.metadata.read_groups.read_group_name",
  "analysis.metadata.read_groups.read_group_qcs.adapter_content",
  "analysis.metadata.read_groups.read_group_qcs.basic_statistics",
  "analysis.metadata.read_groups.read_group_qcs.created_datetime",
  "analysis.metadata.read_groups.read_group_qcs.encoding",
  "analysis.metadata.read_groups.read_group_qcs.fastq_name",
  "analysis.metadata.read_groups.read_group_qcs.kmer_content",
  "analysis.metadata.read_groups.read_group_qcs.overrepresented_sequences",
  "analysis.metadata.read_groups.read_group_qcs.per_base_n_content",
  "analysis.metadata.read_groups.read_group_qcs.per_base_sequence_content",
  "analysis.metadata.read_groups.read_group_qcs.per_base_sequence_quality",
  "analysis.metadata.read_groups.read_group_qcs.per_sequence_gc_content",
  "analysis.metadata.read_groups.read_group_qcs.per_sequence_quality_score",
  "analysis.metadata.read_groups.read_group_qcs.per_tile_sequence_quality",
  "analysis.metadata.read_groups.read_group_qcs.percent_gc_content",
  "analysis.metadata.read_groups.read_group_qcs.read_group_qc_id",
  "analysis.metadata.read_groups.read_group_qcs.sequence_duplication_levels",
  "analysis.metadata.read_groups.read_group_qcs.sequence_length_distribution",
  "analysis.metadata.read_groups.read_group_qcs.state",
  "analysis.metadata.read_groups.read_group_qcs.submitter_id",
  "analysis.metadata.read_groups.read_group_qcs.total_sequences",
  "analysis.metadata.read_groups.read_group_qcs.updated_datetime",
  "analysis.metadata.read_groups.read_group_qcs.workflow_end_datetime",
  "analysis.metadata.read_groups.read_group_qcs.workflow_link",
  "analysis.metadata.read_groups.read_group_qcs.workflow_start_datetime",
  "analysis.metadata.read_groups.read_group_qcs.workflow_type",
  "analysis.metadata.read_groups.read_group_qcs.workflow_version",
  "analysis.metadata.read_groups.read_length",
  "analysis.metadata.read_groups.rin",
  "analysis.metadata.read_groups.sequencing_center",
  "analysis.metadata.read_groups.sequencing_date",
  "analysis.metadata.read_groups.single_cell_library",
  "analysis.metadata.read_groups.size_selection_range",
  "analysis.metadata.read_groups.spike_ins_concentration",
  "analysis.metadata.read_groups.spike_ins_fasta",
  "analysis.metadata.read_groups.state",
  "analysis.metadata.read_groups.submitter_id",
  "analysis.metadata.read_groups.target_capture_kit",
  "analysis.metadata.read_groups.target_capture_kit_catalog_number",
  "analysis.metadata.read_groups.target_capture_kit_name",
  "analysis.metadata.read_groups.target_capture_kit_target_region",
  "analysis.metadata.read_groups.target_capture_kit_vendor",
  "analysis.metadata.read_groups.target_capture_kit_version",
  "analysis.metadata.read_groups.to_trim_adapter_sequence",
  "analysis.metadata.read_groups.updated_datetime",
  "analysis.metadata.read_groups.RIN",
  "analysis.state",
  "analysis.submitter_id",
  "analysis.updated_datetime",
  "analysis.workflow_end_datetime",
  "analysis.workflow_link",
  "analysis.workflow_start_datetime",
  "analysis.workflow_type",
  "analysis.workflow_version",
  "annotations.annotation_id",
  "annotations.case_id",
  "annotations.case_submitter_id",
  "annotations.category",
  "annotations.classification",
  "annotations.created_datetime",
  "annotations.creator",
  "annotations.entity_id",
  "annotations.entity_submitter_id",
  "annotations.entity_type",
  "annotations.legacy_created_datetime",
  "annotations.legacy_updated_datetime",
  "annotations.notes",
  "annotations.state",
  "annotations.status",
  "annotations.submitter_id",
  "annotations.updated_datetime",
  "archive.archive_id",
  "archive.created_datetime",
  "archive.data_category",
  "archive.data_format",
  "archive.data_type",
  "archive.error_type",
  "archive.file_name",
  "archive.file_size",
  "archive.md5sum",
  "archive.revision",
  "archive.state",
  "archive.state_comment",
  "archive.submitter_id",
  "archive.updated_datetime",
  "associated_entities.case_id",
  "associated_entities.entity_id",
  "associated_entities.entity_submitter_id",
  "associated_entities.entity_type",
  "average_base_quality",
  "average_insert_size",
  "average_read_length",
  "cancer_dna_fraction",
  "cases.aliquot_ids",
  "cases.analyte_ids",
  "cases.annotations.annotation_id",
  "cases.annotations.case_id",
  "cases.annotations.case_submitter_id",
  "cases.annotations.category",
  "cases.annotations.classification",
  "cases.annotations.created_datetime",
  "cases.annotations.creator",
  "cases.annotations.entity_id",
  "cases.annotations.entity_submitter_id",
  "cases.annotations.entity_type",
  "cases.annotations.legacy_created_datetime",
  "cases.annotations.legacy_updated_datetime",
  "cases.annotations.notes",
  "cases.annotations.state",
  "cases.annotations.status",
  "cases.annotations.submitter_id",
  "cases.annotations.updated_datetime",
  "cases.case_id",
  "cases.consent_type",
  "cases.created_datetime",
  "cases.days_to_consent",
  "cases.days_to_lost_to_followup",
  "cases.demographic.age_at_index",
  "cases.demographic.age_is_obfuscated",
  "cases.demographic.cause_of_death",
  "cases.demographic.cause_of_death_source",
  "cases.demographic.country_of_birth",
  "cases.demographic.country_of_residence_at_enrollment",
  "cases.demographic.created_datetime",
  "cases.demographic.days_to_birth",
  "cases.demographic.days_to_death",
  "cases.demographic.demographic_id",
  "cases.demographic.education_level",
  "cases.demographic.ethnicity",
  "cases.demographic.gender",
  "cases.demographic.marital_status",
  "cases.demographic.occupation_duration_years",
  "cases.demographic.premature_at_birth",
  "cases.demographic.race",
  "cases.demographic.state",
  "cases.demographic.submitter_id",
  "cases.demographic.updated_datetime",
  "cases.demographic.vital_status",
  "cases.demographic.weeks_gestation_at_birth",
  "cases.demographic.year_of_birth",
  "cases.demographic.year_of_death",
  "cases.diagnoses.adrenal_hormone",
  "cases.diagnoses.age_at_diagnosis",
  "cases.diagnoses.ajcc_clinical_m",
  "cases.diagnoses.ajcc_clinical_n",
  "cases.diagnoses.ajcc_clinical_stage",
  "cases.diagnoses.ajcc_clinical_t",
  "cases.diagnoses.ajcc_pathologic_m",
  "cases.diagnoses.ajcc_pathologic_n",
  "cases.diagnoses.ajcc_pathologic_stage",
  "cases.diagnoses.ajcc_pathologic_t",
  "cases.diagnoses.ajcc_staging_system_edition",
  "cases.diagnoses.ann_arbor_b_symptoms",
  "cases.diagnoses.ann_arbor_b_symptoms_described",
  "cases.diagnoses.ann_arbor_clinical_stage",
  "cases.diagnoses.ann_arbor_extranodal_involvement",
  "cases.diagnoses.ann_arbor_pathologic_stage",
  "cases.diagnoses.annotations.annotation_id",
  "cases.diagnoses.annotations.case_id",
  "cases.diagnoses.annotations.case_submitter_id",
  "cases.diagnoses.annotations.category",
  "cases.diagnoses.annotations.classification",
  "cases.diagnoses.annotations.created_datetime",
  "cases.diagnoses.annotations.creator",
  "cases.diagnoses.annotations.entity_id",
  "cases.diagnoses.annotations.entity_submitter_id",
  "cases.diagnoses.annotations.entity_type",
  "cases.diagnoses.annotations.legacy_created_datetime",
  "cases.diagnoses.annotations.legacy_updated_datetime",
  "cases.diagnoses.annotations.notes",
  "cases.diagnoses.annotations.state",
  "cases.diagnoses.annotations.status",
  "cases.diagnoses.annotations.submitter_id",
  "cases.diagnoses.annotations.updated_datetime",
  "cases.diagnoses.best_overall_response",
  "cases.diagnoses.burkitt_lymphoma_clinical_variant",
  "cases.diagnoses.calgb_risk_group",
  "cases.diagnoses.cancer_detection_method",
  "cases.diagnoses.child_pugh_classification",
  "cases.diagnoses.clark_level",
  "cases.diagnoses.classification_of_tumor",
  "cases.diagnoses.cog_liver_stage",
  "cases.diagnoses.cog_neuroblastoma_risk_group",
  "cases.diagnoses.cog_renal_stage",
  "cases.diagnoses.cog_rhabdomyosarcoma_risk_group",
  "cases.diagnoses.contiguous_organ_invaded",
  "cases.diagnoses.created_datetime",
  "cases.diagnoses.days_to_best_overall_response",
  "cases.diagnoses.days_to_diagnosis",
  "cases.diagnoses.days_to_last_follow_up",
  "cases.diagnoses.days_to_last_known_disease_status",
  "cases.diagnoses.days_to_recurrence",
  "cases.diagnoses.diagnosis_id",
  "cases.diagnoses.diagnosis_is_primary_disease",
  "cases.diagnoses.double_expressor_lymphoma",
  "cases.diagnoses.double_hit_lymphoma",
  "cases.diagnoses.eln_risk_classification",
  "cases.diagnoses.enneking_msts_grade",
  "cases.diagnoses.enneking_msts_metastasis",
  "cases.diagnoses.enneking_msts_stage",
  "cases.diagnoses.enneking_msts_tumor_site",
  "cases.diagnoses.ensat_clinical_m",
  "cases.diagnoses.ensat_pathologic_n",
  "cases.diagnoses.ensat_pathologic_stage",
  "cases.diagnoses.ensat_pathologic_t",
  "cases.diagnoses.esophageal_columnar_dysplasia_degree",
  "cases.diagnoses.esophageal_columnar_metaplasia_present",
  "cases.diagnoses.fab_morphology_code",
  "cases.diagnoses.figo_stage",
  "cases.diagnoses.figo_staging_edition_year",
  "cases.diagnoses.first_symptom_longest_duration",
  "cases.diagnoses.first_symptom_prior_to_diagnosis",
  "cases.diagnoses.gastric_esophageal_junction_involvement",
  "cases.diagnoses.gleason_grade_group",
  "cases.diagnoses.gleason_grade_tertiary",
  "cases.diagnoses.gleason_patterns_percent",
  "cases.diagnoses.gleason_score",
  "cases.diagnoses.goblet_cells_columnar_mucosa_present",
  "cases.diagnoses.icd_10_code",
  "cases.diagnoses.igcccg_stage",
  "cases.diagnoses.inpc_grade",
  "cases.diagnoses.inpc_histologic_group",
  "cases.diagnoses.inrg_stage",
  "cases.diagnoses.inss_stage",
  "cases.diagnoses.international_prognostic_index",
  "cases.diagnoses.irs_group",
  "cases.diagnoses.irs_stage",
  "cases.diagnoses.ishak_fibrosis_score",
  "cases.diagnoses.iss_stage",
  "cases.diagnoses.last_known_disease_status",
  "cases.diagnoses.laterality",
  "cases.diagnoses.margin_distance",
  "cases.diagnoses.margins_involved_site",
  "cases.diagnoses.masaoka_stage",
  "cases.diagnoses.max_tumor_bulk_site",
  "cases.diagnoses.medulloblastoma_molecular_classification",
  "cases.diagnoses.melanoma_known_primary",
  "cases.diagnoses.metastasis_at_diagnosis",
  "cases.diagnoses.metastasis_at_diagnosis_site",
  "cases.diagnoses.method_of_diagnosis",
  "cases.diagnoses.micropapillary_features",
  "cases.diagnoses.mitosis_karyorrhexis_index",
  "cases.diagnoses.mitotic_count",
  "cases.diagnoses.morphology",
  "cases.diagnoses.ovarian_specimen_status",
  "cases.diagnoses.ovarian_surface_involvement",
  "cases.diagnoses.papillary_renal_cell_type",
  "cases.diagnoses.pathology_details.additional_pathology_findings",
  "cases.diagnoses.pathology_details.anaplasia_present",
  "cases.diagnoses.pathology_details.anaplasia_present_type",
  "cases.diagnoses.pathology_details.bone_marrow_malignant_cells",
  "cases.diagnoses.pathology_details.breslow_thickness",
  "cases.diagnoses.pathology_details.circumferential_resection_margin",
  "cases.diagnoses.pathology_details.columnar_mucosa_present",
  "cases.diagnoses.pathology_details.consistent_pathology_review",
  "cases.diagnoses.pathology_details.created_datetime",
  "cases.diagnoses.pathology_details.days_to_pathology_detail",
  "cases.diagnoses.pathology_details.dysplasia_degree",
  "cases.diagnoses.pathology_details.dysplasia_type",
  "cases.diagnoses.pathology_details.epithelioid_cell_percent",
  "cases.diagnoses.pathology_details.extracapsular_extension",
  "cases.diagnoses.pathology_details.extracapsular_extension_present",
  "cases.diagnoses.pathology_details.extranodal_extension",
  "cases.diagnoses.pathology_details.extrascleral_extension",
  "cases.diagnoses.pathology_details.extrathyroid_extension",
  "cases.diagnoses.pathology_details.greatest_tumor_dimension",
  "cases.diagnoses.pathology_details.gross_tumor_weight",
  "cases.diagnoses.pathology_details.histologic_progression_type",
  "cases.diagnoses.pathology_details.largest_extrapelvic_peritoneal_focus",
  "cases.diagnoses.pathology_details.lymph_node_dissection_method",
  "cases.diagnoses.pathology_details.lymph_node_dissection_site",
  "cases.diagnoses.pathology_details.lymph_node_involved_site",
  "cases.diagnoses.pathology_details.lymph_node_involvement",
  "cases.diagnoses.pathology_details.lymph_nodes_positive",
  "cases.diagnoses.pathology_details.lymph_nodes_removed",
  "cases.diagnoses.pathology_details.lymph_nodes_tested",
  "cases.diagnoses.pathology_details.lymphatic_invasion_present",
  "cases.diagnoses.pathology_details.margin_status",
  "cases.diagnoses.pathology_details.measurement_type",
  "cases.diagnoses.pathology_details.measurement_unit",
  "cases.diagnoses.pathology_details.metaplasia_present",
  "cases.diagnoses.pathology_details.micrometastasis_present",
  "cases.diagnoses.pathology_details.morphologic_architectural_pattern",
  "cases.diagnoses.pathology_details.necrosis_percent",
  "cases.diagnoses.pathology_details.necrosis_present",
  "cases.diagnoses.pathology_details.non_nodal_regional_disease",
  "cases.diagnoses.pathology_details.non_nodal_tumor_deposits",
  "cases.diagnoses.pathology_details.number_proliferating_cells",
  "cases.diagnoses.pathology_details.pathology_detail_id",
  "cases.diagnoses.pathology_details.percent_tumor_invasion",
  "cases.diagnoses.pathology_details.percent_tumor_nuclei",
  "cases.diagnoses.pathology_details.perineural_invasion_present",
  "cases.diagnoses.pathology_details.peripancreatic_lymph_nodes_positive",
  "cases.diagnoses.pathology_details.peripancreatic_lymph_nodes_tested",
  "cases.diagnoses.pathology_details.prcc_type",
  "cases.diagnoses.pathology_details.prostatic_chips_positive_count",
  "cases.diagnoses.pathology_details.prostatic_chips_total_count",
  "cases.diagnoses.pathology_details.prostatic_involvement_percent",
  "cases.diagnoses.pathology_details.residual_tumor",
  "cases.diagnoses.pathology_details.residual_tumor_measurement",
  "cases.diagnoses.pathology_details.rhabdoid_percent",
  "cases.diagnoses.pathology_details.rhabdoid_present",
  "cases.diagnoses.pathology_details.sarcomatoid_percent",
  "cases.diagnoses.pathology_details.sarcomatoid_present",
  "cases.diagnoses.pathology_details.size_extraocular_nodule",
  "cases.diagnoses.pathology_details.spindle_cell_percent",
  "cases.diagnoses.pathology_details.state",
  "cases.diagnoses.pathology_details.submitter_id",
  "cases.diagnoses.pathology_details.transglottic_extension",
  "cases.diagnoses.pathology_details.tumor_burden",
  "cases.diagnoses.pathology_details.tumor_depth_descriptor",
  "cases.diagnoses.pathology_details.tumor_depth_measurement",
  "cases.diagnoses.pathology_details.tumor_infiltrating_lymphocytes",
  "cases.diagnoses.pathology_details.tumor_infiltrating_macrophages",
  "cases.diagnoses.pathology_details.tumor_largest_dimension_diameter",
  "cases.diagnoses.pathology_details.tumor_length_measurement",
  "cases.diagnoses.pathology_details.tumor_level_prostate",
  "cases.diagnoses.pathology_details.tumor_shape",
  "cases.diagnoses.pathology_details.tumor_thickness",
  "cases.diagnoses.pathology_details.tumor_width_measurement",
  "cases.diagnoses.pathology_details.updated_datetime",
  "cases.diagnoses.pathology_details.vascular_invasion_present",
  "cases.diagnoses.pathology_details.vascular_invasion_type",
  "cases.diagnoses.pathology_details.zone_of_origin_prostate",
  "cases.diagnoses.pediatric_kidney_staging",
  "cases.diagnoses.peritoneal_fluid_cytological_status",
  "cases.diagnoses.pregnant_at_diagnosis",
  "cases.diagnoses.primary_diagnosis",
  "cases.diagnoses.primary_disease",
  "cases.diagnoses.primary_gleason_grade",
  "cases.diagnoses.prior_malignancy",
  "cases.diagnoses.prior_treatment",
  "cases.diagnoses.progression_or_recurrence",
  "cases.diagnoses.residual_disease",
  "cases.diagnoses.satellite_nodule_present",
  "cases.diagnoses.secondary_gleason_grade",
  "cases.diagnoses.site_of_resection_or_biopsy",
  "cases.diagnoses.sites_of_involvement",
  "cases.diagnoses.sites_of_involvement_count",
  "cases.diagnoses.state",
  "cases.diagnoses.submitter_id",

In [9]:
# Campos de interesse para a requisição ao endpoint
fields = [
    'access',
    'cases.case_id',
    'contamination',
    'contamination_error',
    'data_category',
    'data_format',
    'data_type',
    'error_type',
    'experimental_strategy',
    'file_id',
    'file_name',
    'file_size',
    'state'
]
fields = ','.join(fields)

# Parâmetros para a requisição ao endpoint
params = {
    'fields': fields,
    'format': 'json'
}

# Busca por alguns dos objetos API
response = requests.post(
    url=FILES_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields, 'size': '3'}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Printa um dos objetos do conteúdo da resposta
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

[
  {
    "id": "65087f06-5ab3-4eb0-b9df-752dadd4fbe2",
    "data_format": "TSV",
    "cases": [
      {
        "case_id": "8d8f2522-7dde-4dea-a9f6-8394f97d9152"
      }
    ],
    "access": "controlled",
    "file_name": "TARGET-AML.5904b65c-e712-4f9c-b163-cf5bba5189c1.star_fusion.rna_fusion.tsv",
    "file_id": "65087f06-5ab3-4eb0-b9df-752dadd4fbe2",
    "data_type": "Transcript Fusion",
    "data_category": "Structural Variation",
    "state": "released",
    "experimental_strategy": "RNA-Seq",
    "file_size": 780
  },
  {
    "id": "eb2953ae-792d-425c-8616-ef1308d1f56e",
    "data_format": "TSV",
    "cases": [
      {
        "case_id": "8d8f2522-7dde-4dea-a9f6-8394f97d9152"
      }
    ],
    "access": "open",
    "file_name": "63ab7e0b-7264-4cde-a35d-94c30ec3942e.mirnaseq.isoforms.quantification.txt",
    "file_id": "eb2953ae-792d-425c-8616-ef1308d1f56e",
    "error_type": null,
    "data_type": "Isoform Expression Quantification",
    "data_category": "Transcriptome Profiling",
    "state": "released",
    "experimental_strategy": "miRNA-Seq",
    "file_size": 240142
  },
  {
    "id": "3e99d0d2-1601-4c82-b5aa-6050f6f343bd",
    "data_format": "BAM",
    "access": "controlled",
    "cases": [
      {
        "case_id": "8d8f2522-7dde-4dea-a9f6-8394f97d9152"
      }
    ],
    "file_name": "4e2f3a20-e8a2-4711-995a-c97261572dc3.rna_seq.genomic.gdc_realn.bam",
    "file_id": "3e99d0d2-1601-4c82-b5aa-6050f6f343bd",
    "data_type": "Aligned Reads",
    "data_category": "Sequencing Reads",
    "state": "released",
    "experimental_strategy": "RNA-Seq",
    "file_size": 13544323883
  }
]

## `annotations`

In [10]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{ANNOTATIONS_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON e printa os campos do endpoint
json_response = json.loads(response.content.decode('utf-8'))
json_response_str = json.dumps(json_response['fields'], indent=2)
print(json_response_str)

[
  "annotation_autocomplete",
  "annotation_id",
  "case_id",
  "case_submitter_id",
  "category",
  "classification",
  "created_datetime",
  "entity_id",
  "entity_submitter_id",
  "entity_type",
  "legacy_created_datetime",
  "legacy_updated_datetime",
  "notes",
  "project.code",
  "project.dbgap_accession_number",
  "project.disease_type",
  "project.intended_release_date",
  "project.name",
  "project.primary_site",
  "project.program.dbgap_accession_number",
  "project.program.name",
  "project.program.program_id",
  "project.project_id",
  "project.releasable",
  "project.released",
  "project.state",
  "state",
  "status",
  "submitter_id",
  "updated_datetime"
]

In [11]:
# Campos disponíveis no endpoint
fields = [
    'annotation_autocomplete',
    'annotation_id',
    'case_id',
    'case_submitter_id',
    'category',
    'classification',
    'created_datetime',
    'entity_id',
    'entity_submitter_id',
    'entity_type',
    'legacy_created_datetime',
    'legacy_updated_datetime',
    'notes',
    'project.code',
    'project.dbgap_accession_number',
    'project.disease_type',
    'project.intended_release_date',
    'project.name',
    'project.primary_site',
    'project.program.dbgap_accession_number',
    'project.program.name',
    'project.program.program_id',
    'project.project_id',
    'project.releasable',
    'project.released',
    'project.state',
    'state',
    'status',
    'submitter_id',
    'updated_datetime'
]
fields = ','.join(fields)

# Busca por um dos objetos da API
response = requests.post(
    url=ANNOTATIONS_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': fields, 'size': '1'}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Printa um dos objetos do conteúdo da resposta
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

[
  {
    "id": "57be1bbf-2aff-4eef-a885-0e61bf51471a",
    "entity_submitter_id": "TARGET-AML-somaticsniper-protected_10.0_new_maf",
    "notes": "TARGET MAFs are now aliquot-level.  Project-level MAFs were moved as of DR23",
    "project": {
      "primary_site": [
        "Unknown",
        "Hematopoietic and reticuloendothelial systems"
      ],
      "dbgap_accession_number": "phs000465",
      "project_id": "TARGET-AML",
      "disease_type": [
        "Not Applicable",
        "Myeloid Leukemias"
      ],
      "name": "Acute Myeloid Leukemia",
      "releasable": true,
      "state": "open",
      "program": {
        "dbgap_accession_number": "phs000218",
        "program_id": "f1c391e9-8488-55a8-b777-302e786ea11d",
        "name": "TARGET"
      },
      "released": true
    },
    "classification": "Redaction",
    "entity_id": "ad0b04dd-9cae-45c6-8775-5ea631ab4639",
    "created_datetime": "2020-04-02T17:03:21.323270-05:00",
    "annotation_id": "57be1bbf-2aff-4eef-a885-0e61bf51471a",
    "entity_type": "aggregated_somatic_mutation",
    "updated_datetime": "2020-04-02T17:03:21.323270-05:00",
    "case_id": "d1b986d2-1317-5ee7-ab78-441ea68500f0",
    "state": "released",
    "category": "General",
    "status": "Approved",
    "case_submitter_id": "TARGET-20-PAEEYP"
  }
]

## `data`

In [12]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{DATA_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON e a printa
json_response = json.loads(response.content.decode('utf-8'))
json_response_str = json.dumps(json_response, indent=2)
print(json_response_str)

{
  "message": "_mapping not found"
}

# Processamento Inicial

## Total de Projetos

In [13]:
# Mapeia todas as informações contidas no endpoint
response = requests.get(f'{PROJECTS_ENDPOINT}/_mapping')

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))

# Armazena os campos contidos no endpoint
fields_projects = json.dumps(json_response['fields'])[1:-2]
fields_projects = fields_projects.replace('"', '')
fields_projects = fields_projects.replace(' ', '')

In [14]:
# Busca por todos os objetos do endpoint
response = requests.post(
    url=PROJECTS_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json={'fields': 'name'}
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))

# Armazena total de projetos contidos no TCGA
total_projects = json.dumps(json_response['data']['pagination']['total'])
print(f'Total de projetos no TCGA: {total_projects}')

Total de projetos no TCGA: 86

In [15]:
# Parâmetros para a requisição ao endpoint
params = {
    'fields': fields_projects,
    'size': total_projects
}

# Busca por todos os objetos do endpoint
response = requests.post(
    url=PROJECTS_ENDPOINT,
    headers={'Content-Type': 'application/json'},
    json=params
)

# Converte o conteúdo da resposta para JSON
json_response = json.loads(response.content.decode('utf-8'))['data']['hits']

# Transforma os valores booleanos do JSON em strings
for index in range(len(json_response)):
    obj = json_response[index]
    for key in obj:
        if isinstance(obj[key], bool): 
            obj[key] = str(obj[key])

# Converte o JSON para um DataFrame pandas
df_all_projects = pd.json_normalize(json_response)

# Printa o DataFrame parcialmente
df_all_projects.head()

,id,primary_site,dbgap_accession_number,project_id,disease_type,name,releasable,state,released,summary.file_count,summary.data_categories,summary.experimental_strategies,summary.case_count,summary.file_size,program.dbgap_accession_number,program.program_id,program.name
0,TARGET-AML,"[Unknown, Hematopoietic and reticuloendothelia...",phs000465,TARGET-AML,"[Not Applicable, Myeloid Leukemias]",Acute Myeloid Leukemia,True,open,True,51339,"[{'file_count': 12095, 'case_count': 806, 'dat...","[{'file_count': 28629, 'case_count': 2280, 'ex...",2492,104391798872383,phs000218,f1c391e9-8488-55a8-b777-302e786ea11d,TARGET
1,MATCH-Z1I,"[Bronchus and lung, Gallbladder, Pancreas, Unk...",phs002058,MATCH-Z1I,"[Squamous Cell Neoplasms, Epithelial Neoplasms...",Genomic Characterization CS-MATCH-0007 Arm Z1I,False,open,True,660,"[{'file_count': 327, 'case_count': 24, 'data_c...","[{'file_count': 374, 'case_count': 24, 'experi...",26,2396549656405,None,893b0820-b50b-5c75-85f5-3b028e251811,MATCH
2,HCMI-CMDC,"[Breast, Rectum, Nasal cavity and middle ear, ...",None,HCMI-CMDC,"[Cystic, Mucinous and Serous Neoplasms, Ductal...",NCI Cancer Model Development for the Human Can...,True,open,True,20761,"[{'file_count': 8450, 'case_count': 278, 'data...","[{'file_count': 8096, 'case_count': 276, 'expe...",278,130722797290059,phs001486,a5448c11-d46a-56aa-a5e1-5c1aa06404df,HCMI
3,MATCH-W,"[Breast, Renal pelvis, Corpus uteri, Bladder, ...",phs001948,MATCH-W,"[Cystic, Mucinous and Serous Neoplasms, Ductal...",Genomic Characterization CS-MATCH-0007 Arm W,False,open,True,1091,"[{'file_count': 535, 'case_count': 44, 'data_c...","[{'file_count': 614, 'case_count': 44, 'experi...",45,3929920960515,None,893b0820-b50b-5c75-85f5-3b028e251811,MATCH
4,MATCH-Z1D,"[Breast, Corpus uteri, Bones, joints and artic...",phs001859,MATCH-Z1D,"[Cystic, Mucinous and Serous Neoplasms, Ductal...",Genomic Characterization CS-MATCH-0007 Arm Z1D,False,open,True,891,"[{'file_count': 440, 'case_count': 34, 'data_c...","[{'file_count': 504, 'case_count': 34, 'experi...",36,3282605560716,None,893b0820-b50b-5c75-85f5-3b028e251811,MATCH

## Projetos Lançados com miRNA-Seq e RNA-Seq

In [16]:
# Filtra os projetos lançados pelo TCGA e remove as colunas desnecessárias
df_projects = df_all_projects \
    .query('released == "True"') \
    .drop(
        columns=[
            'id',
            'releasable',
            'released',
            'state',
            'summary.data_categories',
            'summary.file_count',
            'summary.file_size'
        ]
    )

# Inicializa listas para a contagem de casos com miRNA-Seq e RNA-Seq nos projetos
miRNA_Seq_case_count = [0] * df_projects.shape[0]
RNA_Seq_case_count = [0] * df_projects.shape[0]

# Preenche listas com a contagem de casos com miRNA-Seq e RNA-Seq em cada projeto
for index in range(df_projects.shape[0]):
    for info in df_projects['summary.experimental_strategies'][index]:
        if info['experimental_strategy'] in ['miRNA-Seq', 'RNA-Seq']:
            if info['experimental_strategy'] == 'miRNA-Seq':
                miRNA_Seq_case_count[index] = info['case_count']
            else:
                RNA_Seq_case_count[index] = info['case_count']

# Adiciona a contagem de casos de miRNA-Seq e RNA-Seq ao DataFrame
df_projects['miRNA-Seq_case_count'] = miRNA_Seq_case_count
df_projects['RNA-Seq_case_count'] = RNA_Seq_case_count

# Filtra os projetos com miRNA-Seq e RNA-Seq como estratégia experimental
df_projects = df_projects \
    .query('(`miRNA-Seq_case_count` > 0) & (`RNA-Seq_case_count` > 0)') \
    .drop(columns='summary.experimental_strategies') \
    .reset_index(drop=True)

# Reorganiza e renomeia as colunas do DataFrame
columns = [
    'project_id',
    'dbgap_accession_number',
    'name',
    'primary_site',
    'disease_type',
    'summary.case_count',
    'miRNA-Seq_case_count',
    'RNA-Seq_case_count',
    'program.program_id',
    'program.dbgap_accession_number',
    'program.name'
]
df_projects = df_projects[columns] \
    .rename(
        columns={
            'name': 'project_name',
            'summary.case_count': 'case_count',
            'program.program_id': 'program_id',
            'program.dbgap_accession_number': 'program_dbgap_accession_number',
            'program.name': 'program_name'
        }
    )

In [17]:
# Printa o DataFrame de projetos
pd.set_option('display.max_colwidth', 100)
df_projects

,project_id,dbgap_accession_number,project_name,primary_site,disease_type,case_count,miRNA-Seq_case_count,RNA-Seq_case_count,program_id,program_dbgap_accession_number,program_name
0,TARGET-AML,phs000465,Acute Myeloid Leukemia,"[Unknown, Hematopoietic and reticuloendothelial systems]","[Not Applicable, Myeloid Leukemias]",2492,1836,2280,f1c391e9-8488-55a8-b777-302e786ea11d,phs000218,TARGET
1,HCMI-CMDC,None,NCI Cancer Model Development for the Human Cancer Model Initiative,"[Breast, Rectum, Nasal cavity and middle ear, Bronchus and lung, Other and unspecified parts of ...","[Cystic, Mucinous and Serous Neoplasms, Ductal and Lobular Neoplasms, Adenomas and Adenocarcinom...",278,271,277,a5448c11-d46a-56aa-a5e1-5c1aa06404df,phs001486,HCMI
2,TCGA-PCPG,None,Pheochromocytoma and Paraganglioma,"[Other endocrine glands and related structures, Heart, mediastinum, and pleura, Connective, subc...",[Paragangliomas and Glomus Tumors],179,179,179,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
3,TCGA-THYM,None,Thymoma,"[Heart, mediastinum, and pleura, Thymus]",[Thymic Epithelial Neoplasms],124,124,120,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
4,TCGA-PAAD,None,Pancreatic Adenocarcinoma,[Pancreas],"[Cystic, Mucinous and Serous Neoplasms, Ductal and Lobular Neoplasms, Adenomas and Adenocarcinom...",185,178,178,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
5,TCGA-STAD,None,Stomach Adenocarcinoma,[Stomach],"[Cystic, Mucinous and Serous Neoplasms, Adenomas and Adenocarcinomas]",443,436,415,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
6,TCGA-TGCT,None,Testicular Germ Cell Tumors,[Testis],[Germ Cell Neoplasms],263,150,150,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
7,TCGA-SARC,None,Sarcoma,"[Bones, joints and articular cartilage of limbs, Uterus, NOS, Corpus uteri, Other and unspecifie...","[Lipomatous Neoplasms, Synovial-like Neoplasms, Fibromatous Neoplasms, Nerve Sheath Tumors, Myom...",261,259,259,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
8,TCGA-PRAD,None,Prostate Adenocarcinoma,[Prostate gland],"[Cystic, Mucinous and Serous Neoplasms, Adenomas and Adenocarcinomas, Ductal and Lobular Neoplasms]",500,494,497,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
9,TCGA-READ,None,Rectum Adenocarcinoma,"[Rectum, Rectosigmoid junction, Unknown, Colon, Connective, subcutaneous and other soft tissues]","[Cystic, Mucinous and Serous Neoplasms, Adenomas and Adenocarcinomas]",172,161,167,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
10,TCGA-UCS,None,Uterine Carcinosarcoma,"[Uterus, NOS]",[Complex Mixed and Stromal Neoplasms],57,57,57,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
11,TCGA-UVM,None,Uveal Melanoma,[Eye and adnexa],[Nevi and Melanomas],80,80,80,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
12,REBC-THYR,None,Comprehensive genomic characterization of radiation-related papillary thyroid cancer in the Ukraine,[Thyroid gland],"[Adenomas and Adenocarcinomas, Epithelial Neoplasms, NOS]",449,437,438,e0b1fbd1-2a75-5c16-b93a-6c506addec68,phs001134,REBC
13,TARGET-ALL-P2,phs000464,Acute Lymphoblastic Leukemia - Phase II,[Hematopoietic and reticuloendothelial systems],[Lymphoid Leukemias],1587,191,469,f1c391e9-8488-55a8-b777-302e786ea11d,phs000218,TARGET
14,TARGET-ALL-P3,None,Acute Lymphoblastic Leukemia - Phase III,"[Hematopoietic and reticuloendothelial systems, Unknown]","[Lymphoid Leukemias, Not Applicable, Leukemias, NOS, Myeloid Leukemias]",191,38,110,f1c391e9-8488-55a8-b777-302e786ea11d,phs000218,TARGET
15,MP2PRT-WT,phs001965,Molecular Profiling to Predict Response to Treatment - Wilms Tumor,[Kidney],"[Neoplasms, NOS]",52,52,52,710af5f1-9fd6-567e-9e10-226082994325,None,MP2PRT
16,TCGA-KICH,None,Kidney Chromophobe,[Kidney],[Adenomas and Adenocarcinomas],113,66,66,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
17,TCGA-HNSC,None,Head and Neck Squamous Cell Carcinoma,"[Larynx, Oropharynx, Other and unspecified parts of mouth, Base of tongue, Lip, Tonsil, Floor of...",[Squamous Cell Neoplasms],528,524,521,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
18,TCGA-LUAD,None,Lung Adenocarcinoma,[Bronchus and lung],"[Cystic, Mucinous and Serous Neoplasms, Adenomas and Adenocarcinomas, Acinar Cell Neoplasms]",585,513,517,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
19,TCGA-LIHC,None,Liver Hepatocellular Carcinoma,[Liver and intrahepatic bile ducts],[Adenomas and Adenocarcinomas],377,373,371,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
20,TCGA-LUSC,None,Lung Squamous Cell Carcinoma,[Bronchus and lung],[Squamous Cell Neoplasms],504,478,501,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
21,TCGA-MESO,None,Mesothelioma,"[Bronchus and lung, Heart, mediastinum, and pleura]",[Mesothelial Neoplasms],87,87,87,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
22,TCGA-LAML,None,Acute Myeloid Leukemia,[Hematopoietic and reticuloendothelial systems],[Myeloid Leukemias],200,188,151,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
23,TCGA-LGG,None,Brain Lower Grade Glioma,[Brain],[Gliomas],516,512,516,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
24,TCGA-KIRP,None,Kidney Renal Papillary Cell Carcinoma,[Kidney],[Adenomas and Adenocarcinomas],291,291,290,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
25,TCGA-KIRC,None,Kidney Renal Clear Cell Carcinoma,[Kidney],[Adenomas and Adenocarcinomas],537,516,533,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
26,CGCI-BLGSP,phs000527,Burkitt Lymphoma Genome Sequencing Project,[Hematopoietic and reticuloendothelial systems],[Mature B-Cell Lymphomas],324,278,283,d339a424-ad52-5351-a499-493973249414,phs000235,CGCI
27,CGCI-HTMCP-CC,phs000528,HIV+ Tumor Molecular Characterization Project - Cervical Cancer,[Cervix uteri],"[Squamous Cell Neoplasms, Adenomas and Adenocarcinomas, Complex Epithelial Neoplasms, Epithelial...",212,118,123,d339a424-ad52-5351-a499-493973249414,phs000235,CGCI
28,CGCI-HTMCP-DLBCL,phs000529,HIV+ Tumor Molecular Characterization Project - Diffuse Large B-Cell Lymphoma,[Hematopoietic and reticuloendothelial systems],[Mature B-Cell Lymphomas],70,60,55,d339a424-ad52-5351-a499-493973249414,phs000235,CGCI
29,CGCI-HTMCP-LC,phs000530,HIV+ Tumor Molecular Characterization Project - Lung Cancer,[Bronchus and lung],"[Squamous Cell Neoplasms, Epithelial Neoplasms, NOS, Complex Epithelial Neoplasms, Neoplasms, NO...",39,37,38,d339a424-ad52-5351-a499-493973249414,phs000235,CGCI
30,TCGA-ACC,None,Adrenocortical Carcinoma,[Adrenal gland],[Adenomas and Adenocarcinomas],92,80,79,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
31,TARGET-WT,phs000471,High-Risk Wilms Tumor,[Kidney],[Complex Mixed and Stromal Neoplasms],652,127,125,f1c391e9-8488-55a8-b777-302e786ea11d,phs000218,TARGET
32,TCGA-BLCA,None,Bladder Urothelial Carcinoma,[Bladder],"[Transitional Cell Papillomas and Carcinomas, Squamous Cell Neoplasms, Adenomas and Adenocarcino...",412,409,406,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
33,TARGET-RT,phs000470,Rhabdoid Tumor,"[Lip, Liver and intrahepatic bile ducts, Kidney]",[Complex Mixed and Stromal Neoplasms],69,66,63,f1c391e9-8488-55a8-b777-302e786ea11d,phs000218,TARGET
34,TCGA-DLBC,None,Lymphoid Neoplasm Diffuse Large B-cell Lymphoma,"[Hematopoietic and reticuloendothelial systems, Breast, Lymph nodes, Colon, Small intestine, Bra...","[Mature B-Cell Lymphomas, Not Reported]",58,47,48,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
35,TCGA-CHOL,None,Cholangiocarcinoma,"[Liver and intrahepatic bile ducts, Other and unspecified parts of biliary tract, Gallbladder]",[Adenomas and Adenocarcinomas],51,36,36,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
36,TCGA-CESC,None,Cervical Squamous Cell Carcinoma and Endocervical Adenocarcinoma,[Cervix uteri],"[Cystic, Mucinous and Serous Neoplasms, Squamous Cell Neoplasms, Complex Epithelial Neoplasms, A...",307,307,304,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
37,TCGA-COAD,None,Colon Adenocarcinoma,"[Colon, Rectosigmoid junction]","[Cystic, Mucinous and Serous Neoplasms, Adenomas and Adenocarcinomas, Complex Epithelial Neoplas...",461,444,458,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
38,CPTAC-3,phs001287,"CPTAC-Brain, Head and Neck, Kidney, Lung, Pancreas, Uterus","[Uterus, NOS, Other and unspecified urinary organs, Breast, Pancreas, Unknown, Bronchus and lung...","[Lipomatous Neoplasms, Squamous Cell Neoplasms, Epithelial Neoplasms, NOS, Transitional Cell Pap...",1345,1316,1342,fe856b91-d4a1-51dd-ba58-ea71644ff5cd,None,CPTAC
39,TCGA-BRCA,None,Breast Invasive Carcinoma,[Breast],"[Squamous Cell Neoplasms, Adnexal and Skin Appendage Neoplasms, Epithelial Neoplasms, NOS, Compl...",1098,1079,1095,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
40,TCGA-ESCA,None,Esophageal Carcinoma,"[Stomach, Esophagus]","[Cystic, Mucinous and Serous Neoplasms, Squamous Cell Neoplasms, Adenomas and Adenocarcinomas]",185,184,184,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
41,TCGA-GBM,None,Glioblastoma Multiforme,[Brain],"[Gliomas, Not Reported]",617,13,168,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
42,CPTAC-2,phs000892,"CPTAC-Breast, Colon, Ovary","[Rectum, Breast, Other and unspecified female genital organs, Colon, Retroperitoneum and periton...","[Squamous Cell Neoplasms, Not Reported, Cystic, Mucinous and Serous Neoplasms, Adenomas and Aden...",342,310,340,fe856b91-d4a1-51dd-ba58-ea71644ff5cd,None,CPTAC
43,TCGA-OV,None,Ovarian Serous Cystadenocarcinoma,[Ovary],"[Not Reported, Cystic, Mucinous and Serous Neoplasms]",608,489,422,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
44,TCGA-THCA,None,Thyroid Carcinoma,[Thyroid gland],"[Epithelial Neoplasms, NOS, Adenomas and Adenocarcinomas]",507,506,505,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
45,TCGA-SKCM,None,Skin Cutaneous Melanoma,[Skin],[Nevi and Melanomas],470,448,469,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA
46,TCGA-UCEC,None,Uterine Corpus Endometrial Carcinoma,"[Uterus, NOS, Corpus uteri]","[Epithelial Neoplasms, NOS, Cystic, Mucinous and Serous Neoplasms, Not Reported, Adenomas and Ad...",560,550,557,b80aa962-9650-5110-b3eb-bd087da808db,phs000178,TCGA

## Casos com miRNA-Seq e RNA-Seq

In [18]:
# Campos de interesse para a requisição ao endpoint
fields_cases = [
    'disease_type',
    'files.access',
    'files.data_category',
    'files.data_format',
    'files.data_type',
    'files.file_id',
    'files.experimental_strategy',
    'primary_site',
    'project.project_id',
]
fields_cases = ','.join(fields_cases)

# Inicializa o DataFrame de casos e arquivos
df_cases_and_files = pd.DataFrame()

# Busca pelos casos com miRNA-Seq e RNA-Seq de cada projeto de interesse
for index in range(df_projects.shape[0]):
    # Filtros empregados na requisição ao endpoint
    filters = {
        'op': 'and',
        'content': [
            {
                'op': '=',
                'content': {
                    'field': 'project.project_id',
                    'value': df_projects['project_id'][index]
                }
            },
            {
                'op': 'in',
                'content': {
                    'field': 'files.experimental_strategy',
                    'value': ['miRNA-Seq', 'RNA-Seq']
                }
            }
        ]
    }

    # Parâmetros para a requisição ao endpoint
    params = {
        'fields': fields_cases,
        'filters': filters,
        'size': str(df_projects['case_count'][index])
    }

    # Busca por todos os objetos do endpoint
    response = requests.post(
        url=CASES_ENDPOINT,
        headers={'Content-Type': 'application/json'},
        json=params
    )

    # Converte o conteúdo da resposta para JSON
    json_response = json.loads(response.content.decode('utf-8'))

    # Converte o JSON para um DataFrame pandas
    df_project_cases = pd.json_normalize(json_response['data']['hits'])

    # Concatena os casos deste projeto com os restantes
    if df_cases_and_files.empty == False:
        df_cases_and_files = pd.concat(
            [df_cases_and_files, df_project_cases], ignore_index=True
        )
    else:
        df_cases_and_files = df_project_cases.copy()

# Renomeia algumas colunas do DataFrame
df_cases_and_files = df_cases_and_files.rename(
    columns={'id': 'case_id', 'project.project_id': 'project_id'}
)

In [19]:
# Printa o DataFrame de casos e arquivos
df_cases_and_files

,case_id,primary_site,disease_type,files,project_id
0,58771370-5082-485e-ac68-13edfbd9ef0c,Hematopoietic and reticuloendothelial systems,Myeloid Leukemias,"[{'data_format': 'XLSX', 'access': 'open', 'file_id': '52fd584b-9ca3-4f7e-bdd5-fd9dce3d630b', 'd...",TARGET-AML
1,28da5b52-29ed-4817-a678-9206c5164da0,Hematopoietic and reticuloendothelial systems,Myeloid Leukemias,"[{'data_format': 'XLSX', 'access': 'open', 'file_id': '52fd584b-9ca3-4f7e-bdd5-fd9dce3d630b', 'd...",TARGET-AML
2,28dae019-4d93-42bf-9bb3-8e6e21bc1d29,Hematopoietic and reticuloendothelial systems,Myeloid Leukemias,"[{'data_format': 'TSV', 'access': 'controlled', 'file_id': '46894ff9-3571-4878-8134-d0ad10a3fd89...",TARGET-AML
3,28f7e68c-e0ab-4fb0-b835-2e506cb0012d,Hematopoietic and reticuloendothelial systems,Myeloid Leukemias,"[{'data_format': 'BAM', 'access': 'controlled', 'file_id': '87a249be-2899-4294-9fea-4a7578971f2d...",TARGET-AML
4,28ffdfb9-f051-4424-ad35-e6633e6bf42e,Hematopoietic and reticuloendothelial systems,Myeloid Leukemias,"[{'data_format': 'XLSX', 'access': 'open', 'file_id': '52fd584b-9ca3-4f7e-bdd5-fd9dce3d630b', 'd...",TARGET-AML
...,...,...,...,...,...
16606,a798a8cc-4e72-4a8c-9e20-74a14deafd12,Corpus uteri,Adenomas and Adenocarcinomas,"[{'data_format': 'BCR Biotab', 'access': 'open', 'file_id': '3eefa637-ec64-42fa-8d0d-c740de10666...",TCGA-UCEC
16607,fe2e89f7-8f4d-420a-a551-4877cf0fd1d3,Corpus uteri,Adenomas and Adenocarcinomas,"[{'data_format': 'SVS', 'access': 'open', 'file_id': '0d29b22e-3f4f-462a-bc73-c93237cb3867', 'da...",TCGA-UCEC
16608,db3a4986-55d5-4ecc-be73-59725dce3c33,Corpus uteri,Adenomas and Adenocarcinomas,"[{'data_format': 'MAF', 'access': 'controlled', 'file_id': 'eb6f7308-a02d-414c-b2c0-7c86a7651df5...",TCGA-UCEC
16609,ff6b5fc8-0572-4b58-b3a5-bcda41badbc8,Corpus uteri,"Cystic, Mucinous and Serous Neoplasms","[{'data_format': 'BAM', 'access': 'controlled', 'file_id': 'b0c765b4-4804-451c-812a-9cf2e86b570f...",TCGA-UCEC
16610,43476c88-86bc-4a65-9327-f0d24a41c971,Corpus uteri,Adenomas and Adenocarcinomas,"[{'data_format': 'BCR Biotab', 'access': 'open', 'file_id': '3eefa637-ec64-42fa-8d0d-c740de10666...",TCGA-UCEC

## Arquivos com miRNA-Seq e RNA-Seq

In [20]:
# Explode as listas com dicionário sobre os arquivos dos casos
df_cases = df_cases_and_files.explode('files')

# Filtra os arquivos dos casos relacionados a miRNA-Seq e RNA-Seq
key = 'experimental_strategy'
df_cases = df_cases[
    df_cases['files'].apply(
        lambda x: (
            key in x and (x[key] == 'miRNA-Seq' or x[key] == 'RNA-Seq')
        )
    )
]

# Explode os dicionários com as informações sobre os arquivos de interesse
df_files = pd.json_normalize(df_cases['files'])

# Remove a coluna referente aos arquivos e redefine os índices do DataFrame
df_cases = df_cases.drop(columns='files').reset_index(drop=True)

# Concatena os DataFrames e define o DataFrame de arquivos
df_files = pd.concat([df_cases, df_files], axis='columns')
df_files = df_files.drop(columns=['primary_site', 'disease_type', 'project_id'])
df_files = df_files[[
    'file_id',
    'access',
    'data_format',
    'data_type',
    'data_category',
    'experimental_strategy',
    'case_id'
]]

# Define o DataFrame de casos
df_cases = df_cases \
    .drop_duplicates() \
    .reset_index(drop=True)

In [21]:
# Printa o DataFrame de casos
df_cases

,case_id,primary_site,disease_type,project_id
0,58771370-5082-485e-ac68-13edfbd9ef0c,Hematopoietic and reticuloendothelial systems,Myeloid Leukemias,TARGET-AML
1,28da5b52-29ed-4817-a678-9206c5164da0,Hematopoietic and reticuloendothelial systems,Myeloid Leukemias,TARGET-AML
2,28dae019-4d93-42bf-9bb3-8e6e21bc1d29,Hematopoietic and reticuloendothelial systems,Myeloid Leukemias,TARGET-AML
3,28f7e68c-e0ab-4fb0-b835-2e506cb0012d,Hematopoietic and reticuloendothelial systems,Myeloid Leukemias,TARGET-AML
4,28ffdfb9-f051-4424-ad35-e6633e6bf42e,Hematopoietic and reticuloendothelial systems,Myeloid Leukemias,TARGET-AML
...,...,...,...,...
16606,a798a8cc-4e72-4a8c-9e20-74a14deafd12,Corpus uteri,Adenomas and Adenocarcinomas,TCGA-UCEC
16607,fe2e89f7-8f4d-420a-a551-4877cf0fd1d3,Corpus uteri,Adenomas and Adenocarcinomas,TCGA-UCEC
16608,db3a4986-55d5-4ecc-be73-59725dce3c33,Corpus uteri,Adenomas and Adenocarcinomas,TCGA-UCEC
16609,ff6b5fc8-0572-4b58-b3a5-bcda41badbc8,Corpus uteri,"Cystic, Mucinous and Serous Neoplasms",TCGA-UCEC
16610,43476c88-86bc-4a65-9327-f0d24a41c971,Corpus uteri,Adenomas and Adenocarcinomas,TCGA-UCEC

In [22]:
# Printa o DataFrame de arquivos
df_files

,file_id,access,data_format,data_type,data_category,experimental_strategy,case_id
0,7e37b56e-4a47-4e14-aa0c-2317e31f3e53,controlled,TSV,Transcript Fusion,Structural Variation,RNA-Seq,58771370-5082-485e-ac68-13edfbd9ef0c
1,2b213562-4c34-4976-9563-ef2e581eb993,controlled,BAM,Aligned Reads,Sequencing Reads,RNA-Seq,58771370-5082-485e-ac68-13edfbd9ef0c
2,4188fa7a-7b11-47ae-ad63-701f5a2ffecb,controlled,BEDPE,Transcript Fusion,Structural Variation,RNA-Seq,58771370-5082-485e-ac68-13edfbd9ef0c
3,dd250c15-0be7-4243-b147-d4c872587844,controlled,BEDPE,Transcript Fusion,Structural Variation,RNA-Seq,58771370-5082-485e-ac68-13edfbd9ef0c
4,619cea2a-d035-4979-ad83-b7863eefc337,controlled,BAM,Aligned Reads,Sequencing Reads,RNA-Seq,58771370-5082-485e-ac68-13edfbd9ef0c
...,...,...,...,...,...,...,...
229791,d78ca382-fc44-48fb-b40e-3c56bab0ba99,open,TXT,miRNA Expression Quantification,Transcriptome Profiling,miRNA-Seq,43476c88-86bc-4a65-9327-f0d24a41c971
229792,af52e052-4b18-41f6-8647-8370405c4b00,controlled,TSV,Splice Junction Quantification,Transcriptome Profiling,RNA-Seq,43476c88-86bc-4a65-9327-f0d24a41c971
229793,f491ad0e-78db-4ed0-9d80-9d26bb0f736d,controlled,BAM,Aligned Reads,Sequencing Reads,miRNA-Seq,43476c88-86bc-4a65-9327-f0d24a41c971
229794,36cd1c9b-ab47-4a09-96d6-848cd59c08dd,open,TSV,Gene Expression Quantification,Transcriptome Profiling,RNA-Seq,43476c88-86bc-4a65-9327-f0d24a41c971
229795,b78f9db8-2723-4045-b0a8-c43e02f3b871,open,TXT,Isoform Expression Quantification,Transcriptome Profiling,miRNA-Seq,43476c88-86bc-4a65-9327-f0d24a41c971